import { useState } from "react";
import { useParams, Link } from "wouter";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { getChildPlan } from "@workspace/api-client-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { ChildNav } from "@/components/child-nav";
import { ChevronLeft, Target, BookOpen, Calendar, Star, Trophy, Clock, RefreshCw } from "lucide-react";

interface Goal {
  id: string;
  title: string;
  description: string;
  targetDate: string;
  targetSurahCount: number;
  currentCount: number;
  type: string;
  autoGenerated: boolean;
}

function GoalCard({ goal, onReset }: { goal: Goal; onReset: () => void }) {
  const progress = Math.min(100, Math.round((goal.currentCount / goal.targetSurahCount) * 100));
  const targetDate = new Date(goal.targetDate);
  const today = new Date();
  const daysLeft = Math.max(0, Math.ceil((targetDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)));
  const isCompleted = goal.currentCount >= goal.targetSurahCount;

  return (
    <div className={`p-4 rounded-xl border ${isCompleted ? "border-emerald-300 bg-emerald-50" : "border-border bg-card"}`}>
      <div className="flex items-start justify-between mb-2">
        <div className="flex-1">
          <p className="text-sm font-semibold text-foreground">{goal.title}</p>
          <p className="text-xs text-muted-foreground mt-0.5">{goal.description}</p>
        </div>
        {isCompleted ? (
          <span className="text-2xl ml-2">🏆</span>
        ) : (
          <button onClick={onReset} className="ml-2 p-1 rounded-lg hover:bg-muted transition-colors" title="Reset goal">
            <RefreshCw size={12} className="text-muted-foreground" />
          </button>
        )}
      </div>
      <Progress value={progress} className="h-2 mb-2" />
      <div className="flex items-center justify-between text-xs text-muted-foreground">
        <span>{goal.currentCount} / {goal.targetSurahCount} surahs</span>
        {!isCompleted && (
          <span className="flex items-center gap-1">
            <Clock size={10} />
            {daysLeft === 0 ? "Due today" : `${daysLeft} days left`}
          </span>
        )}
        {isCompleted && <span className="text-emerald-600 font-medium">Completed!</span>}
      </div>
      {!isCompleted && (
        <p className="text-[10px] text-muted-foreground mt-1">
          Target: {targetDate.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
        </p>
      )}
    </div>
  );
}

export default function PlanPage() {
  const { childId } = useParams<{ childId: string }>();
  const qc = useQueryClient();

  const { data: plan, isLoading } = useQuery({
    queryKey: ["plan", childId],
    queryFn: () => getChildPlan(parseInt(childId))
  });

  const resetGoalsMutation = useMutation({
    mutationFn: () => fetch(`/api/children/${childId}/goals`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ goals: null })
    }).then(r => r.json()),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["plan", childId] })
  });

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background pb-24">
        <div className="pattern-bg h-40" />
        <div className="max-w-lg mx-auto px-4 -mt-6 space-y-4">
          {[1,2,3].map(i => <Skeleton key={i} className="h-40 rounded-2xl" />)}
        </div>
      </div>
    );
  }

  if (!plan) return null;

  const AGE_GROUP_LABELS: Record<string, string> = {
    toddler: "Seeds of Faith (Ages 3–6)",
    child: "Building Foundation (Ages 7–10)",
    preteen: "Deepening Knowledge (Ages 11–14)",
    teen: "Path to Hifz (Ages 15+)"
  };

  const goals: Goal[] = (plan as any).goals || [];
  const practiceMinutes: number = (plan as any).practiceMinutesPerDay || 20;

  return (
    <div className="min-h-screen bg-background pb-24">
      <div className="pattern-bg text-white px-4 pt-8 pb-12">
        <div className="max-w-lg mx-auto">
          <Link href={`/child/${childId}`}>
            <button className="flex items-center gap-1 text-emerald-200 text-sm mb-4"><ChevronLeft size={16} /> Dashboard</button>
          </Link>
          <h1 className="text-xl font-bold">Learning Plan</h1>
          <p className="text-emerald-200 text-sm mt-1">{AGE_GROUP_LABELS[plan.ageGroup]}</p>
          <div className="flex items-center gap-2 mt-2">
            <div className="flex items-center gap-1 bg-white/15 rounded-full px-3 py-1">
              <Clock size={12} className="text-emerald-200" />
              <span className="text-xs text-emerald-100">{practiceMinutes} min/day</span>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-lg mx-auto px-4 -mt-6 space-y-4">

        {/* Long-term Goals */}
        {goals.length > 0 && (
          <Card className="border-primary/20">
            <CardContent className="p-4">
              <div className="flex items-center justify-between mb-3">
                <h2 className="font-semibold text-foreground flex items-center gap-2">
                  <Trophy size={16} className="text-amber-500" /> Your Goals
                </h2>
                <button
                  onClick={() => resetGoalsMutation.mutate()}
                  className="text-[10px] text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1"
                >
                  <RefreshCw size={9} /> Reset to auto
                </button>
              </div>
              <div className="space-y-3">
                {goals.map((goal: Goal) => (
                  <GoalCard
                    key={goal.id}
                    goal={goal}
                    onReset={() => resetGoalsMutation.mutate()}
                  />
                ))}
              </div>
              <p className="text-[10px] text-muted-foreground mt-3 text-center">
                Goals are auto-calculated based on your {practiceMinutes} min/day practice time
              </p>
            </CardContent>
          </Card>
        )}

        {/* Description */}
        <Card className="border-border shadow-sm">
          <CardContent className="p-4">
            <p className="text-sm text-foreground leading-relaxed">{plan.description}</p>
          </CardContent>
        </Card>

        {/* Current phase */}
        <Card className="border-primary/20 bg-primary/5">
          <CardContent className="p-4">
            <div className="flex items-center gap-2 mb-2">
              <Target size={16} className="text-primary" />
              <h2 className="font-semibold text-foreground">Current Phase</h2>
            </div>
            <Badge className="bg-primary/15 text-primary border-0 mb-2">{plan.currentPhase.phaseName}</Badge>
            <p className="text-sm text-foreground mb-3">{plan.currentPhase.description}</p>
            <div className="flex flex-wrap gap-1">
              {plan.currentPhase.surahs.map((s: string) => (
                <Badge key={s} variant="secondary" className="text-xs">{s}</Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Weekly goals */}
        <Card className="border-border">
          <CardContent className="p-4">
            <h2 className="font-semibold text-foreground mb-3 flex items-center gap-2">
              <Calendar size={16} className="text-primary" /> Weekly Goals
            </h2>
            <div className="grid grid-cols-2 gap-3">
              <div className="text-center p-3 bg-primary/5 rounded-xl">
                <p className="text-2xl font-bold text-primary">{plan.weeklyGoal.memorizationDays}</p>
                <p className="text-xs text-muted-foreground mt-0.5">Memorization days</p>
              </div>
              <div className="text-center p-3 bg-amber-50 rounded-xl">
                <p className="text-2xl font-bold text-amber-600">{plan.weeklyGoal.reviewDays}</p>
                <p className="text-xs text-muted-foreground mt-0.5">Review days</p>
              </div>
              <div className="text-center p-3 bg-blue-50 rounded-xl">
                <p className="text-2xl font-bold text-blue-600">{plan.weeklyGoal.storyDays}</p>
                <p className="text-xs text-muted-foreground mt-0.5">Story days</p>
              </div>
              <div className="text-center p-3 bg-rose-50 rounded-xl">
                <p className="text-2xl font-bold text-rose-500">{plan.weeklyGoal.duasDays}</p>
                <p className="text-xs text-muted-foreground mt-0.5">Du'a practice days</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Milestones */}
        <Card className="border-border">
          <CardContent className="p-4">
            <h2 className="font-semibold text-foreground mb-3 flex items-center gap-2">
              <Star size={16} className="text-amber-500" /> Milestones
            </h2>
            <div className="space-y-3">
              {plan.milestones.map((m: { id: string; title: string; description: string; targetSurahs: string[]; reward: string }) => (
                <div key={m.id} className="p-3 rounded-xl bg-amber-50/70 border border-amber-200/50">
                  <div className="flex items-start justify-between mb-1">
                    <p className="font-semibold text-sm text-foreground">{m.title}</p>
                    <span className="text-sm">{m.reward.split(" ")[0]}</span>
                  </div>
                  <p className="text-xs text-muted-foreground mb-2">{m.description}</p>
                  <div className="flex flex-wrap gap-1">
                    {m.targetSurahs.map(s => (
                      <Badge key={s} variant="secondary" className="text-[10px]">{s}</Badge>
                    ))}
                  </div>
                  <p className="text-xs text-amber-700 mt-2 font-medium">🎁 {m.reward}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Tajweed rules */}
        <Card className="border-border">
          <CardContent className="p-4">
            <h2 className="font-semibold text-foreground mb-3 flex items-center gap-2">
              <BookOpen size={16} className="text-primary" /> Tajweed Rules for This Level
            </h2>
            <div className="space-y-3">
              {plan.tajweedRules.map((rule: { rule: string; description: string; ageIntroduced: number }) => (
                <div key={rule.rule} className="flex items-start gap-3 p-3 rounded-xl bg-muted/40">
                  <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-xs font-bold text-primary flex-shrink-0 mt-0.5">
                    {rule.ageIntroduced}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-foreground">{rule.rule}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">{rule.description}</p>
                    <p className="text-[10px] text-primary mt-1">Introduced at age {rule.ageIntroduced}</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <ChildNav childId={childId} />
    </div>
  );
}
