import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const TOTAL_PAGES = 604;
const TOTAL_AYAHS = 6236;
const SURAH_VERSE_COUNTS = [
  7, 286, 200, 176, 120, 165, 206, 75, 129, 109,
  123, 111, 43, 52, 99, 128, 111, 110, 98, 135,
  112, 78, 118, 64, 77, 227, 93, 88, 69, 60,
  34, 30, 73, 54, 45, 83, 182, 88, 75, 85,
  54, 53, 89, 59, 37, 35, 38, 29, 18, 45,
  60, 49, 62, 55, 78, 96, 29, 22, 24, 13,
  14, 11, 11, 18, 12, 12, 30, 52, 52, 44,
  28, 28, 20, 56, 40, 31, 50, 40, 46, 42,
  29, 19, 36, 25, 22, 17, 19, 26, 30, 20,
  15, 21, 11, 8, 8, 19, 5, 8, 8, 11,
  11, 8, 3, 9, 5, 4, 7, 3, 6, 3,
  5, 4, 5, 6,
] as const;

type QuranCom1405AyahRect = readonly [
  surah: number,
  ayah: number,
  line: number,
  minX: number,
  maxX: number,
  minY: number,
  maxY: number,
  glyphCount: number,
];

type QuranCom1405PageCoords = {
  ayahRects?: QuranCom1405AyahRect[];
};

type QuranCom1405AyahInfo = {
  pages?: Record<string, QuranCom1405PageCoords | undefined>;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../../..");
const sourcePath = resolve(
  repoRoot,
  "artifacts/noor-mobile/assets/mushaf-pages/quran-com-1405/ayahinfo_1920.json",
);
const outputPath = resolve(
  repoRoot,
  "artifacts/api-server/src/data/quran-com-1405-pages.ts",
);

function validateAndBuildPageByAyah(data: QuranCom1405AyahInfo): Map<string, number> {
  const pages = data.pages ?? {};
  const pageNumbers = Object.keys(pages).map(Number).sort((a, b) => a - b);
  if (
    pageNumbers.length !== TOTAL_PAGES ||
    pageNumbers[0] !== 1 ||
    pageNumbers[pageNumbers.length - 1] !== TOTAL_PAGES
  ) {
    throw new Error(`Expected pages 1-${TOTAL_PAGES}, found ${pageNumbers.length} page entries.`);
  }

  const pageByAyah = new Map<string, number>();
  for (let pageNumber = 1; pageNumber <= TOTAL_PAGES; pageNumber += 1) {
    const page = pages[String(pageNumber)];
    if (!page) {
      throw new Error(`Missing Quran.com 1405 page ${pageNumber}.`);
    }

    for (const rect of page.ayahRects ?? []) {
      const [surah, ayah] = rect;
      const maxAyah = SURAH_VERSE_COUNTS[surah - 1];
      if (!Number.isInteger(surah) || !Number.isInteger(ayah) || !maxAyah || ayah < 1 || ayah > maxAyah) {
        throw new Error(`Invalid ayah rectangle ${surah}:${ayah} on page ${pageNumber}.`);
      }

      const key = `${surah}:${ayah}`;
      const previousPage = pageByAyah.get(key);
      if (previousPage !== undefined && previousPage !== pageNumber) {
        throw new Error(`Ayah ${key} appears on pages ${previousPage} and ${pageNumber}.`);
      }
      pageByAyah.set(key, pageNumber);
    }
  }

  const missing: string[] = [];
  for (let surah = 1; surah <= SURAH_VERSE_COUNTS.length; surah += 1) {
    const ayahCount = SURAH_VERSE_COUNTS[surah - 1];
    for (let ayah = 1; ayah <= ayahCount; ayah += 1) {
      const key = `${surah}:${ayah}`;
      if (!pageByAyah.has(key)) missing.push(key);
    }
  }
  if (missing.length > 0) {
    throw new Error(`Missing ${missing.length} ayah mappings. First missing: ${missing.slice(0, 10).join(", ")}`);
  }
  if (pageByAyah.size !== TOTAL_AYAHS) {
    throw new Error(`Expected ${TOTAL_AYAHS} ayah mappings, found ${pageByAyah.size}.`);
  }

  return pageByAyah;
}

function compareAyahKeys(left: string, right: string) {
  const [leftSurah, leftAyah] = left.split(":").map(Number);
  const [rightSurah, rightAyah] = right.split(":").map(Number);
  return leftSurah === rightSurah ? leftAyah - rightAyah : leftSurah - rightSurah;
}

const source = JSON.parse(readFileSync(sourcePath, "utf8")) as QuranCom1405AyahInfo;
const pageByAyah = validateAndBuildPageByAyah(source);
const entries = [...pageByAyah.entries()].sort(([left], [right]) => compareAyahKeys(left, right));
const pageSet = new Set(entries.map(([, page]) => page));
if (pageSet.size !== TOTAL_PAGES) {
  throw new Error(`Expected mappings to cover ${TOTAL_PAGES} pages, found ${pageSet.size}.`);
}

const body = entries
  .map(([key, page]) => `  ${JSON.stringify(key)}: ${page},`)
  .join("\n");

const output = `// Generated by artifacts/api-server/src/scripts/generate-quran-com-1405-pages.ts.
// Source: artifacts/noor-mobile/assets/mushaf-pages/quran-com-1405/ayahinfo_1920.json
// Do not edit manually.

export const QURAN_COM_1405_TOTAL_PAGES = ${TOTAL_PAGES};
export const QURAN_COM_1405_TOTAL_AYAHS = ${TOTAL_AYAHS};

export const QURAN_COM_1405_SURAH_VERSE_COUNTS: readonly number[] = ${JSON.stringify(SURAH_VERSE_COUNTS)};

export const QURAN_COM_1405_PAGE_BY_AYAH: Readonly<Record<string, number>> = {
${body}
};
`;

writeFileSync(outputPath, output);
console.log(`[ok] Wrote ${entries.length} Quran.com 1405 ayah→page mappings to ${outputPath}.`);
