import { useCallback, useState, type ComponentProps, type ReactNode } from "react";
import {
  ActivityIndicator,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { ChildBottomNav } from "@/src/components/child-bottom-nav";
import { ApiError, apiFetch } from "@/src/lib/api";
import { fetchReviewQueue, type ReviewQueueItem, type ReviewQueueResponse } from "@/src/lib/reviews";
import { getReviewPriorityStyle } from "@/src/lib/review-priority";

type WorkStatus = "not_started" | "in_progress" | "completed";
type IconName = ComponentProps<typeof Ionicons>["name"];

type DashboardChild = {
  name: string;
  avatarEmoji: string;
  streakDays: number;
  totalPoints: number;
  juzCompleted?: number;
  practiceMinutesPerDay?: number;
  hideStories?: boolean;
  hideDuas?: boolean;
};

type ChildDetail = DashboardChild & {
  readPagesPerDay: number;
};

type NewMemorization = {
  surahName: string;
  surahNumber: number;
  currentWorkSurahName?: string;
  currentWorkAyahStart?: number;
  currentWorkAyahEnd?: number;
  ayahStart: number;
  ayahEnd: number;
  pageStart: number;
  pageEnd: number;
  workLabel?: string;
  isReviewOnly?: boolean;
  estimatedMinutes?: number;
};

type DashboardStory = {
  id: number;
  title: string;
};

type DashboardDua = {
  id: number;
  arabic: string;
  transliteration: string;
  translation: string;
};

type Goal = {
  id: string;
  title: string;
  description: string;
  targetDate?: string;
  targetSurahCount?: number;
  currentCount?: number;
  type: string;
  autoGenerated?: boolean;
};

type Achievement = {
  id: string;
  title: string;
  description: string;
  icon: string;
  earned: boolean;
  progress?: number | null;
  target?: number | null;
};

type MemorizationStats = {
  totalSurahsMemorized: number;
  totalVersesMemorized: number;
  juzCompleted: number;
  currentSurah: string | null;
  longestStreak: number;
  weeklyProgress: Array<{
    day: string;
    versesMemorized: number;
    minutesPracticed: number;
  }>;
};

type NextSurah = {
  number: number;
  nameArabic: string;
  nameTransliteration: string;
  nameTranslation: string;
  verseCount: number;
};

type TodayProgress = {
  memStatus: WorkStatus;
  reviewStatus: WorkStatus;
  reviewTargetCount: number | null;
  reviewCompletedCount: number;
};

type ReadingGoal = {
  targetPages: number;
  completedPages: number;
  lastPage: number | null;
  status: WorkStatus;
  isEnabled: boolean;
};

type DashboardResponse = {
  child: DashboardChild;
  todaysPlan: {
    newMemorization: NewMemorization | null;
    story?: DashboardStory | null;
    dua?: DashboardDua | null;
    totalEstimatedMinutes: number;
  };
  memorizationStats?: MemorizationStats;
  recentSessions?: Array<unknown>;
  reviewsDueToday: number;
  nextSurah?: NextSurah | null;
  achievements?: Achievement[];
  goals?: Goal[];
  todayProgress?: TodayProgress;
  readingGoal: ReadingGoal | null;
  upNextMemorization?: NewMemorization | null;
};

type DashboardState =
  | { status: "loading" }
  | { status: "error"; message: string }
  | {
      status: "ok";
      dashboard: DashboardResponse;
      reviews: ReviewQueueResponse | null;
      reviewError: string | null;
      dashboardError: string | null;
    };

type CardTone = {
  accent: string;
  bg: string;
  border: string;
  soft: string;
};

const CARD_TONES: Record<"memorization" | "review" | "reading", CardTone> = {
  memorization: {
    accent: "#2563eb",
    bg: "#f8fbff",
    border: "#bfdbfe",
    soft: "#dbeafe",
  },
  review: {
    accent: "#ea580c",
    bg: "#fffaf5",
    border: "#fed7aa",
    soft: "#ffedd5",
  },
  reading: {
    accent: "#0f766e",
    bg: "#f5fffc",
    border: "#99f6e4",
    soft: "#ccfbf1",
  },
};

const STATUS_COPY: Record<WorkStatus, { label: string; color: string; bg: string; border: string }> = {
  not_started: {
    label: "Ready",
    color: "#2563eb",
    bg: "#eff6ff",
    border: "#bfdbfe",
  },
  in_progress: {
    label: "In progress",
    color: "#b45309",
    bg: "#fffbeb",
    border: "#fde68a",
  },
  completed: {
    label: "Complete",
    color: "#047857",
    bg: "#ecfdf5",
    border: "#a7f3d0",
  },
};

function formatAyahRange(start: number | undefined, end: number | undefined) {
  if (start == null || end == null) return "Ayahs";
  return start === end ? `Ayah ${start}` : `Ayahs ${start}-${end}`;
}

function formatPageRange(start: number | undefined, end: number | undefined) {
  if (start == null || end == null) return null;
  return start === end ? `Page ${start}` : `Pages ${start}-${end}`;
}

function formatDayStreak(days: number) {
  return `${days} day${days === 1 ? "" : "s"}`;
}

function formatPercent(value: number, target: number) {
  if (target <= 0) return 0;
  return Math.max(0, Math.min(100, Math.round((value / target) * 100)));
}

function formatGoalDate(value: string | undefined) {
  if (!value) return null;
  const date = new Date(`${value}T12:00:00`);
  if (Number.isNaN(date.getTime())) return null;
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

function wait(ms: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function describeError(error: unknown) {
  if (error instanceof ApiError) {
    return `${error.message} (${error.path}; cookie=${error.hasCookie ? "yes" : "no"})`;
  }
  if (error instanceof Error) {
    return error.message;
  }
  return "Unknown failure";
}

function fallbackChild(childId: string | undefined, name: string | undefined): ChildDetail {
  return {
    name: name || (childId ? `Child ${childId}` : "Child"),
    avatarEmoji: "?",
    streakDays: 0,
    totalPoints: 0,
    readPagesPerDay: 0,
  };
}

function isValidChildId(childId: string | undefined) {
  return typeof childId === "string" && /^\d+$/.test(childId);
}

function fallbackDashboard(
  child: ChildDetail,
  reviews: ReviewQueueResponse | null,
): DashboardResponse {
  const reviewCount = reviews?.dueToday.length ?? 0;
  const readPagesPerDay = child.readPagesPerDay ?? 0;

  return {
    child: {
      name: child.name,
      avatarEmoji: child.avatarEmoji,
      streakDays: child.streakDays,
      totalPoints: child.totalPoints,
    },
    todaysPlan: {
      newMemorization: null,
      totalEstimatedMinutes: 0,
    },
    reviewsDueToday: reviewCount,
    todayProgress: {
      memStatus: "not_started",
      reviewStatus: "not_started",
      reviewTargetCount: reviewCount,
      reviewCompletedCount: 0,
    },
    readingGoal: {
      targetPages: readPagesPerDay,
      completedPages: 0,
      lastPage: null,
      status: "not_started",
      isEnabled: readPagesPerDay > 0,
    },
  };
}

function WorkCard({
  title,
  eyebrow,
  detail,
  cta,
  tone,
  onPress,
  status,
  children,
}: {
  title: string;
  eyebrow: string;
  detail: string;
  cta: string;
  tone: CardTone;
  onPress: () => void;
  status?: WorkStatus;
  children?: ReactNode;
}) {
  const statusStyle = status ? STATUS_COPY[status] : null;

  return (
    <Pressable
      style={[
        styles.card,
        {
          backgroundColor: tone.bg,
          borderColor: tone.border,
        },
      ]}
      onPress={onPress}
    >
      <View style={styles.cardHeader}>
        <View style={[styles.cardIcon, { backgroundColor: tone.soft }]}>
          <Text style={[styles.cardIconText, { color: tone.accent }]}>
            {title.charAt(0)}
          </Text>
        </View>
        <View style={styles.cardTitleBlock}>
          <Text style={styles.cardEyebrow}>{eyebrow}</Text>
          <Text style={styles.cardLabel}>{title}</Text>
        </View>
        {statusStyle && (
          <View
            style={[
              styles.statusPill,
              {
                backgroundColor: statusStyle.bg,
                borderColor: statusStyle.border,
              },
            ]}
          >
            <Text style={[styles.statusPillText, { color: statusStyle.color }]}>
              {statusStyle.label}
            </Text>
          </View>
        )}
        <Text style={[styles.cardAction, { color: tone.accent }]}>{cta}</Text>
      </View>
      <Text style={styles.cardDetail}>{detail}</Text>
      {children}
    </Pressable>
  );
}

function SectionHeader({
  title,
  action,
  onPress,
}: {
  title: string;
  action?: string;
  onPress?: () => void;
}) {
  return (
    <View style={styles.sectionHeader}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {action && onPress ? (
        <Pressable onPress={onPress}>
          <Text style={styles.sectionAction}>{action}</Text>
        </Pressable>
      ) : null}
    </View>
  );
}

function StatTile({
  label,
  value,
  iconName,
  color,
}: {
  label: string;
  value: string | number;
  iconName: IconName;
  color: string;
}) {
  return (
    <View style={styles.statTile}>
      <View style={[styles.statIcon, { backgroundColor: `${color}14` }]}>
        <Ionicons name={iconName} size={17} color={color} />
      </View>
      <Text style={[styles.statValue, { color }]}>{value}</Text>
      <Text style={styles.statLabel}>{label}</Text>
    </View>
  );
}

function ProgressBar({
  value,
  color,
}: {
  value: number;
  color: string;
}) {
  return (
    <View style={styles.progressTrack}>
      <View style={[styles.progressFill, { width: `${value}%`, backgroundColor: color }]} />
    </View>
  );
}

function GoalPreview({ goal }: { goal: Goal }) {
  const current = goal.currentCount ?? 0;
  const target = goal.targetSurahCount ?? 0;
  const percent = target > 0 ? formatPercent(current, target) : 0;
  const dateLabel = formatGoalDate(goal.targetDate);

  return (
    <View style={styles.goalRow}>
      <View style={styles.goalText}>
        <Text style={styles.goalTitle}>{goal.title}</Text>
        <Text style={styles.goalDetail} numberOfLines={2}>
          {goal.description}
        </Text>
        {target > 0 ? (
          <Text style={styles.goalMeta}>
            {current}/{target} surahs{dateLabel ? ` · by ${dateLabel}` : ""}
          </Text>
        ) : null}
      </View>
      {target > 0 ? (
        <View style={styles.goalProgress}>
          <Text style={styles.goalPercent}>{percent}%</Text>
          <ProgressBar value={percent} color="#2563eb" />
        </View>
      ) : null}
    </View>
  );
}

function AchievementPreview({ achievement }: { achievement: Achievement }) {
  const progress = achievement.progress ?? 0;
  const target = achievement.target ?? 0;
  const percent = achievement.earned ? 100 : target > 0 ? formatPercent(progress, target) : 0;

  return (
    <View style={styles.achievementRow}>
      <View style={[styles.achievementIcon, achievement.earned && styles.achievementIconEarned]}>
        <Text style={styles.achievementEmoji}>{achievement.icon}</Text>
      </View>
      <View style={styles.achievementText}>
        <View style={styles.achievementTitleRow}>
          <Text style={styles.achievementTitle}>{achievement.title}</Text>
          {achievement.earned ? (
            <Text style={styles.earnedText}>Earned</Text>
          ) : target > 0 ? (
            <Text style={styles.achievementProgressText}>
              {progress}/{target}
            </Text>
          ) : null}
        </View>
        <Text style={styles.achievementDetail}>{achievement.description}</Text>
        {!achievement.earned && target > 0 ? (
          <ProgressBar value={percent} color="#f59e0b" />
        ) : null}
      </View>
    </View>
  );
}

function SuggestionCard({
  title,
  detail,
  iconName,
  color,
  onPress,
  children,
}: {
  title: string;
  detail: string;
  iconName: IconName;
  color: string;
  onPress: () => void;
  children?: ReactNode;
}) {
  return (
    <Pressable
      style={[styles.suggestionCard, { borderColor: `${color}33`, backgroundColor: `${color}0d` }]}
      onPress={onPress}
    >
      <View style={[styles.suggestionIcon, { backgroundColor: `${color}18` }]}>
        <Ionicons name={iconName} size={18} color={color} />
      </View>
      <View style={styles.suggestionText}>
        <Text style={styles.suggestionTitle}>{title}</Text>
        <Text style={styles.suggestionDetail} numberOfLines={2}>
          {detail}
        </Text>
        {children}
      </View>
      <Text style={[styles.suggestionAction, { color }]}>More</Text>
    </Pressable>
  );
}

function QuickAction({
  title,
  detail,
  iconName,
  color,
  onPress,
}: {
  title: string;
  detail: string;
  iconName: IconName;
  color: string;
  onPress: () => void;
}) {
  return (
    <Pressable style={styles.quickAction} onPress={onPress}>
      <View style={[styles.quickIcon, { backgroundColor: `${color}14` }]}>
        <Ionicons name={iconName} size={18} color={color} />
      </View>
      <View style={styles.quickText}>
        <Text style={styles.quickTitle}>{title}</Text>
        <Text style={styles.quickDetail}>{detail}</Text>
      </View>
    </Pressable>
  );
}

function ReviewPreviewItem({ item }: { item: ReviewQueueItem }) {
  const priorityStyle = getReviewPriorityStyle(item.reviewPriority);
  const rangeLabel = formatAyahRange(item.ayahStart, item.ayahEnd);

  return (
    <View
      style={[
        styles.reviewPreview,
        {
          backgroundColor: priorityStyle.cardBg,
          borderColor: priorityStyle.border,
        },
      ]}
    >
      <View style={[styles.reviewDot, { backgroundColor: priorityStyle.text }]} />
      <View style={styles.reviewPreviewText}>
        <Text style={styles.reviewSurah} numberOfLines={1}>
          {item.surahName ?? `Surah ${item.surahNumber}`}
        </Text>
        <Text style={styles.reviewRange}>{rangeLabel}</Text>
      </View>
      <Text style={[styles.reviewPriority, { color: priorityStyle.text }]}>
        {priorityStyle.label}
      </Text>
    </View>
  );
}

export default function ChildDashboard() {
  const { childId, name } = useLocalSearchParams<{ childId: string; name: string }>();
  const router = useRouter();
  const [state, setState] = useState<DashboardState>({ status: "loading" });
  const [refreshing, setRefreshing] = useState(false);
  const navChildId = typeof childId === "string" ? childId : undefined;
  const navName = typeof name === "string" ? name : "";
  const navReviewCount =
    state.status === "ok"
      ? state.reviews?.dueToday.length ?? state.dashboard.reviewsDueToday
      : undefined;

  const loadDashboard = useCallback(
    async (mode: "initial" | "refresh" = "initial") => {
      const childIdParam = childId;
      const nameParam = name;

      if (mode === "initial") {
        setState({ status: "loading" });
      } else {
        setRefreshing(true);
      }

      if (!isValidChildId(childIdParam)) {
        setState({
          status: "error",
          message: "This dashboard route is missing a valid child id. Go back and reopen the child profile.",
        });
        setRefreshing(false);
        return;
      }

      try {
        let dashboard: DashboardResponse;
        try {
          dashboard = await apiFetch<DashboardResponse>(
            `/api/children/${childIdParam}/dashboard`,
          );
        } catch {
          await wait(350);
          dashboard = await apiFetch<DashboardResponse>(
            `/api/children/${childIdParam}/dashboard`,
          );
        }
        let reviews: ReviewQueueResponse | null = null;
        let reviewError: string | null = null;

        try {
          reviews = await fetchReviewQueue(childIdParam);
        } catch (e) {
          reviewError = describeError(e);
        }

        setState({
          status: "ok",
          dashboard,
          reviews,
          reviewError,
          dashboardError: null,
        });
      } catch (e) {
        const dashboardError = describeError(e);
        let reviews: ReviewQueueResponse | null = null;
        let reviewError: string | null = null;
        let child: ChildDetail | null = null;

        try {
          reviews = await fetchReviewQueue(childIdParam);
        } catch (reviewFetchError) {
          reviewError = describeError(reviewFetchError);
        }

        try {
          child = await apiFetch<ChildDetail>(`/api/children/${childIdParam}`);
        } catch {
          child = fallbackChild(childIdParam, nameParam);
        }

        setState({
          status: "ok",
          dashboard: fallbackDashboard(child, reviews),
          reviews,
          reviewError,
          dashboardError,
        });
      } finally {
        setRefreshing(false);
      }
    },
    [childId, name],
  );

  useFocusEffect(
    useCallback(() => {
      loadDashboard();
    }, [loadDashboard]),
  );

  function handleCardPress(key: string) {
    if (key === "review") {
      router.push({
        pathname: "/child/[childId]/review",
        params: { childId, name: name ?? "" },
      });
    } else if (key === "reading") {
      router.push({
        pathname: "/child/[childId]/mushaf",
        params: { childId, name: name ?? "" },
      });
    } else if (key === "memorization") {
      router.push({
        pathname: "/child/[childId]/memorization",
        params: { childId, name: name ?? "" },
      });
    }
  }

  function handleTargetsPress() {
    if (!isValidChildId(childId)) return;

    router.push({
      pathname: "/child/[childId]/targets",
      params: { childId, name: name ?? "" },
    });
  }

  function openChildRoute(
    pathname:
      | "/child/[childId]/memorization"
      | "/child/[childId]/review"
      | "/child/[childId]/mushaf"
      | "/child/[childId]/targets"
      | "/child/[childId]/profile"
      | "/child/[childId]/more",
    displayName = name ?? "",
  ) {
    if (!isValidChildId(childId)) return;
    router.push({
      pathname,
      params: { childId, name: displayName },
    });
  }

  function renderContent() {
    if (state.status === "loading") {
      return (
        <View style={styles.center}>
          <ActivityIndicator size="large" color="#2563eb" />
        </View>
      );
    }

    if (state.status === "error") {
      return (
        <View style={styles.center}>
          <Text style={styles.errorText}>{state.message}</Text>
          <Pressable style={styles.retryButton} onPress={() => loadDashboard()}>
            <Text style={styles.retryText}>Retry</Text>
          </Pressable>
        </View>
      );
    }

    const { dashboard, reviews, reviewError, dashboardError } = state;
    const child = dashboard.child;
    const todaysMem = dashboard.todaysPlan.newMemorization;
    const stats = dashboard.memorizationStats;
    const goals = dashboard.goals ?? [];
    const achievements = dashboard.achievements ?? [];
    const earnedAchievements = achievements.filter((achievement) => achievement.earned);
    const todayProgress = dashboard.todayProgress;
    const memStatus = todayProgress?.memStatus ?? "not_started";
    const memSurah = todaysMem?.currentWorkSurahName ?? todaysMem?.surahName;
    const memAyahStart = todaysMem?.currentWorkAyahStart ?? todaysMem?.ayahStart;
    const memAyahEnd = todaysMem?.currentWorkAyahEnd ?? todaysMem?.ayahEnd;
    const memPageLabel = formatPageRange(todaysMem?.pageStart, todaysMem?.pageEnd);
    const memDetail = !todaysMem
      ? stats?.totalSurahsMemorized
        ? "No new memorization assigned today. Keep the memory fresh with review or reading."
        : "No memorization assigned yet. Start with today's first lesson when you're ready."
      : memStatus === "completed"
      ? `${todaysMem.workLabel ?? "Memorization"} complete for ${todaysMem.surahName}.`
      : memStatus === "in_progress"
      ? `${memSurah} is in progress · ${formatAyahRange(memAyahStart, memAyahEnd)}${
          memPageLabel ? ` · ${memPageLabel}` : ""
        }`
      : `${todaysMem.workLabel ?? "New Memorization"} · ${memSurah} · ${formatAyahRange(
          memAyahStart,
          memAyahEnd,
        )}${memPageLabel ? ` · ${memPageLabel}` : ""}`;
    const memCta =
      memStatus === "completed" ? "Done" : memStatus === "in_progress" ? "Continue" : "Start";

    const dueItems = reviews?.dueToday ?? [];
    const reviewedItems = reviews?.reviewedToday ?? [];
    const reviewsDueToday = reviews ? dueItems.length : dashboard.reviewsDueToday;
    const reviewCompletedToday = Math.max(
      todayProgress?.reviewCompletedCount ?? 0,
      reviewedItems.length,
    );
    const reviewTarget =
      todayProgress?.reviewTargetCount != null
        ? Math.max(todayProgress.reviewTargetCount, reviewCompletedToday)
        : reviewsDueToday + reviewCompletedToday;
    const reviewDone =
      todayProgress?.reviewStatus === "completed" ||
      (reviewsDueToday === 0 && reviewCompletedToday > 0);
    const reviewStatusForCard: WorkStatus = reviewDone
      ? "completed"
      : reviewCompletedToday > 0
      ? "in_progress"
      : "not_started";
    const hasReviewActivity =
      reviewsDueToday > 0 ||
      reviewCompletedToday > 0 ||
      todayProgress?.reviewStatus === "in_progress";
    const reviewDetail = reviewDone
      ? `Today's review complete · ${reviewCompletedToday}/${Math.max(
          reviewTarget,
          reviewCompletedToday,
        )} done`
      : reviewsDueToday > 0
      ? `${reviewsDueToday} review${reviewsDueToday === 1 ? "" : "s"} due today${
          reviewCompletedToday > 0 ? ` · ${reviewCompletedToday} done` : ""
        }`
      : reviewError
      ? "Review queue could not refresh."
      : "Review is clear today. A light read still counts toward the habit.";
    const reviewCta = reviewDone ? "Done" : reviewsDueToday > 0 ? "Review" : "Open";

    const readingGoal = dashboard.readingGoal;
    const readingEnabled = !!readingGoal?.isEnabled;
    const readingDetail = !readingEnabled
      ? "No reading goal set yet. Add one from Targets when reading is part of the day."
      : readingGoal.status === "completed"
      ? `Today's reading complete · ${readingGoal.completedPages}/${readingGoal.targetPages} pages`
      : readingGoal.status === "in_progress"
      ? `${readingGoal.completedPages}/${readingGoal.targetPages} pages read · resume page ${
          readingGoal.lastPage ?? 1
        }`
      : `Read ${readingGoal.targetPages} page${
          readingGoal.targetPages === 1 ? "" : "s"
        } today${readingGoal.lastPage ? ` · saved page ${readingGoal.lastPage}` : ""}`;
    const readingCta =
      readingGoal?.status === "completed"
        ? "Done"
        : readingGoal?.status === "in_progress"
        ? "Resume"
        : "Read";
    const readingStatus = readingGoal?.status ?? "not_started";
    const totalMinutes = dashboard.todaysPlan.totalEstimatedMinutes;
    const story = !child.hideStories ? dashboard.todaysPlan.story : null;
    const dua = !child.hideDuas ? dashboard.todaysPlan.dua : null;
    const hasContentSuggestions = !!story || !!dua;
    const upNextMem = dashboard.upNextMemorization;
    const nextWorkTitle = upNextMem
      ? upNextMem.workLabel ?? "Next Memorization"
      : dashboard.nextSurah
      ? "Next Surah"
      : null;
    const nextWorkDetail = upNextMem
      ? `${upNextMem.surahName} · ${formatAyahRange(upNextMem.ayahStart, upNextMem.ayahEnd)}${
          formatPageRange(upNextMem.pageStart, upNextMem.pageEnd)
            ? ` · ${formatPageRange(upNextMem.pageStart, upNextMem.pageEnd)}`
            : ""
        }`
      : dashboard.nextSurah
      ? `${dashboard.nextSurah.nameTransliteration} · ${dashboard.nextSurah.nameTranslation} · ${dashboard.nextSurah.verseCount} verses`
      : null;
    const allPrimaryWorkComplete =
      (!todaysMem || memStatus === "completed") &&
      (reviewDone || reviewsDueToday === 0) &&
      (!readingEnabled || readingGoal?.status === "completed");
    const noPrimaryWork =
      !todaysMem &&
      reviewsDueToday === 0 &&
      reviewCompletedToday === 0 &&
      !readingEnabled;
    const showCompleteBanner = allPrimaryWorkComplete && !noPrimaryWork;

    return (
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.list}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={() => loadDashboard("refresh")}
            tintColor="#2563eb"
          />
        }
      >
        <View style={styles.summaryBand}>
          <Text style={styles.summaryAvatar}>{child.avatarEmoji}</Text>
          <View style={styles.summaryText}>
            <Text style={styles.summaryKicker}>Today</Text>
            <Text style={styles.summaryName}>{child.name}</Text>
            <Text style={styles.summarySubline}>
              {totalMinutes > 0 ? `${totalMinutes} min plan` : "A gentle day is ready"}
            </Text>
          </View>
          <View style={styles.summaryStats}>
            <Text style={styles.summaryStat}>{formatDayStreak(child.streakDays)}</Text>
            <Text style={styles.summaryStatMuted}>{child.totalPoints} pts</Text>
          </View>
        </View>

        {dashboardError && (
          <View style={styles.warningBanner}>
            <Text style={styles.warningText}>
              Today's plan is temporarily unavailable. Pull down to refresh shortly.
            </Text>
          </View>
        )}

        <View style={styles.statsGrid}>
          <StatTile
            label="Surahs"
            value={stats?.totalSurahsMemorized ?? 0}
            iconName="library-outline"
            color="#2563eb"
          />
          <StatTile
            label="Verses"
            value={stats?.totalVersesMemorized ?? 0}
            iconName="text-outline"
            color="#d97706"
          />
          <StatTile
            label="Badges"
            value={earnedAchievements.length}
            iconName="trophy-outline"
            color="#be123c"
          />
        </View>

        {(showCompleteBanner || noPrimaryWork) && (
          <View
            style={[
              styles.dayStateBanner,
              showCompleteBanner ? styles.dayStateComplete : styles.dayStateEmpty,
            ]}
          >
            <Ionicons
              name={showCompleteBanner ? "checkmark-circle-outline" : "leaf-outline"}
              size={19}
              color={showCompleteBanner ? "#047857" : "#0f766e"}
            />
            <Text
              style={[
                styles.dayStateText,
                { color: showCompleteBanner ? "#047857" : "#0f766e" },
              ]}
            >
              {showCompleteBanner
                ? "All core work is complete for today."
                : "No required work is queued. Choose a light review, reading, or target update."}
            </Text>
          </View>
        )}

        <SectionHeader title="Today's Work" />

        <WorkCard
          title="Memorization"
          eyebrow={todaysMem?.isReviewOnly ? "Recitation focus" : "Today's work"}
          detail={memDetail}
          cta={memCta}
          tone={CARD_TONES.memorization}
          onPress={() => handleCardPress("memorization")}
          status={todaysMem ? memStatus : undefined}
        />

        <WorkCard
          title="Review"
          eyebrow="Review queue"
          detail={reviewDetail}
          cta={reviewCta}
          tone={CARD_TONES.review}
          onPress={() => handleCardPress("review")}
          status={hasReviewActivity ? reviewStatusForCard : undefined}
        >
          {dueItems.length > 0 && (
            <View style={styles.reviewPreviewList}>
              {dueItems.slice(0, 3).map((item) => (
                <ReviewPreviewItem key={item.id} item={item} />
              ))}
              {dueItems.length > 3 && (
                <Text style={styles.moreText}>+{dueItems.length - 3} more queued</Text>
              )}
            </View>
          )}
        </WorkCard>

        <WorkCard
          title="Reading"
          eyebrow="Mushaf"
          detail={readingDetail}
          cta={readingCta}
          tone={CARD_TONES.reading}
          onPress={() => handleCardPress("reading")}
          status={readingEnabled ? readingStatus : undefined}
        />

        {nextWorkTitle && nextWorkDetail && (
          <>
            <SectionHeader title="Up Next" />
            <Pressable
              style={styles.nextCard}
              onPress={() => handleCardPress("memorization")}
            >
              <View style={styles.nextNumber}>
                <Text style={styles.nextNumberText}>
                  {upNextMem?.surahNumber ?? dashboard.nextSurah?.number}
                </Text>
              </View>
              <View style={styles.nextText}>
                <Text style={styles.nextTitle}>{nextWorkTitle}</Text>
                <Text style={styles.nextDetail}>{nextWorkDetail}</Text>
              </View>
              {dashboard.nextSurah && !upNextMem ? (
                <Text style={styles.nextArabic}>{dashboard.nextSurah.nameArabic}</Text>
              ) : (
                <Ionicons name="chevron-forward" size={18} color="#2563eb" />
              )}
            </Pressable>
          </>
        )}

        {goals.length > 0 && (
          <>
            <SectionHeader
              title="Goals"
              action="Settings"
              onPress={handleTargetsPress}
            />
            <View style={styles.panel}>
              {goals.slice(0, 2).map((goal) => (
                <GoalPreview key={goal.id} goal={goal} />
              ))}
            </View>
          </>
        )}

        {achievements.length > 0 && (
          <>
            <SectionHeader
              title="Achievements"
              action="More"
              onPress={() => openChildRoute("/child/[childId]/more", child.name)}
            />
            <View style={styles.panel}>
              {achievements.slice(0, 3).map((achievement) => (
                <AchievementPreview key={achievement.id} achievement={achievement} />
              ))}
            </View>
          </>
        )}

        {hasContentSuggestions && (
          <>
            <SectionHeader title="Gentle Extras" />
            <View style={styles.suggestionList}>
              {story && (
                <SuggestionCard
                  title="Today's Story"
                  detail={story.title}
                  iconName="sparkles-outline"
                  color="#2563eb"
                  onPress={() => openChildRoute("/child/[childId]/more", child.name)}
                />
              )}
              {dua && (
                <SuggestionCard
                  title="Today's Du'a"
                  detail={dua.translation}
                  iconName="heart-outline"
                  color="#be123c"
                  onPress={() => openChildRoute("/child/[childId]/more", child.name)}
                >
                  <Text style={styles.duaArabic} numberOfLines={1}>
                    {dua.arabic}
                  </Text>
                </SuggestionCard>
              )}
            </View>
          </>
        )}

        <SectionHeader title="Quick Actions" />
        <View style={styles.quickGrid}>
          <QuickAction
            title="Settings"
            detail="Targets"
            iconName="flag-outline"
            color="#2563eb"
            onPress={handleTargetsPress}
          />
          <QuickAction
            title="Full Quran"
            detail="Read pages"
            iconName="reader-outline"
            color="#0f766e"
            onPress={() => handleCardPress("reading")}
          />
          <QuickAction
            title="Profile"
            detail="Settings"
            iconName="settings-outline"
            color="#4f46e5"
            onPress={() => openChildRoute("/child/[childId]/profile", child.name)}
          />
          <QuickAction
            title="More"
            detail="All tools"
            iconName="grid-outline"
            color="#7c3aed"
            onPress={() => openChildRoute("/child/[childId]/more", child.name)}
          />
        </View>
      </ScrollView>
    );
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()}>
          <Text style={styles.back}>← Back</Text>
        </Pressable>
        <Text style={styles.title}>{name ?? "Dashboard"}</Text>
        <Pressable style={styles.headerRight} onPress={handleTargetsPress}>
          <Text style={styles.targetsText}>Settings</Text>
        </Pressable>
      </View>

      {renderContent()}
      <ChildBottomNav
        active="dashboard"
        childId={navChildId}
        name={navName}
        reviewCount={navReviewCount}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  back: {
    fontSize: 16,
    color: "#2563eb",
    fontWeight: "500",
    width: 70,
  },
  title: {
    flex: 1,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "700",
    color: "#111111",
  },
  headerRight: {
    width: 70,
    alignItems: "flex-end",
  },
  targetsText: {
    fontSize: 14,
    color: "#2563eb",
    fontWeight: "700",
  },
  list: {
    padding: 20,
    gap: 14,
    paddingBottom: 32,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    gap: 16,
  },
  errorText: {
    fontSize: 15,
    color: "#dc2626",
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#2563eb",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  retryText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
  },
  scroll: {
    flex: 1,
  },
  summaryBand: {
    backgroundColor: "#111111",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  summaryAvatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    overflow: "hidden",
    textAlign: "center",
    lineHeight: 48,
    fontSize: 28,
  },
  summaryText: {
    flex: 1,
  },
  summaryKicker: {
    fontSize: 12,
    color: "#d1d5db",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  summaryName: {
    fontSize: 20,
    color: "#ffffff",
    fontWeight: "700",
    marginTop: 2,
  },
  summarySubline: {
    fontSize: 12,
    color: "#d1d5db",
    fontWeight: "600",
    marginTop: 3,
  },
  summaryStats: {
    alignItems: "flex-end",
    gap: 2,
  },
  summaryStat: {
    fontSize: 13,
    color: "#fbbf24",
    fontWeight: "700",
  },
  summaryStatMuted: {
    fontSize: 13,
    color: "#d1d5db",
    fontWeight: "600",
  },
  warningBanner: {
    backgroundColor: "#fffbeb",
    borderWidth: 1,
    borderColor: "#fde68a",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  warningText: {
    color: "#92400e",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  statsGrid: {
    flexDirection: "row",
    gap: 10,
  },
  statTile: {
    flex: 1,
    minHeight: 96,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  statIcon: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  statValue: {
    fontSize: 20,
    fontWeight: "800",
  },
  statLabel: {
    fontSize: 12,
    color: "#666666",
    fontWeight: "700",
  },
  dayStateBanner: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dayStateComplete: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
  },
  dayStateEmpty: {
    backgroundColor: "#f0fdfa",
    borderColor: "#99f6e4",
  },
  dayStateText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  sectionHeader: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: "#111111",
    fontSize: 15,
    fontWeight: "800",
  },
  sectionAction: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "800",
  },
  card: {
    backgroundColor: "#f9fafb",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    gap: 10,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cardIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  cardIconText: {
    fontSize: 18,
    fontWeight: "800",
  },
  cardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  cardEyebrow: {
    fontSize: 12,
    color: "#666666",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  cardLabel: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111111",
    marginTop: 1,
  },
  cardAction: {
    fontSize: 14,
    fontWeight: "700",
  },
  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: "800",
  },
  cardDetail: {
    fontSize: 14,
    color: "#444444",
    lineHeight: 20,
  },
  reviewPreviewList: {
    gap: 8,
    marginTop: 2,
  },
  reviewPreview: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 8,
  },
  reviewDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  reviewPreviewText: {
    flex: 1,
    minWidth: 0,
  },
  reviewSurah: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111111",
  },
  reviewRange: {
    fontSize: 12,
    color: "#666666",
    marginTop: 1,
  },
  reviewPriority: {
    fontSize: 12,
    fontWeight: "700",
  },
  moreText: {
    fontSize: 12,
    color: "#666666",
    fontWeight: "600",
  },
  nextCard: {
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  nextNumber: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#dbeafe",
    alignItems: "center",
    justifyContent: "center",
  },
  nextNumberText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "800",
  },
  nextText: {
    flex: 1,
    minWidth: 0,
  },
  nextTitle: {
    color: "#111111",
    fontSize: 15,
    fontWeight: "800",
  },
  nextDetail: {
    color: "#555555",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  nextArabic: {
    color: "#2563eb",
    fontSize: 20,
    fontWeight: "700",
  },
  panel: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    overflow: "hidden",
  },
  goalRow: {
    padding: 14,
    flexDirection: "row",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  goalText: {
    flex: 1,
    minWidth: 0,
  },
  goalTitle: {
    color: "#111111",
    fontSize: 14,
    fontWeight: "800",
  },
  goalDetail: {
    color: "#666666",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  goalMeta: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 5,
  },
  goalProgress: {
    width: 76,
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
  },
  goalPercent: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "800",
  },
  progressTrack: {
    width: "100%",
    height: 6,
    backgroundColor: "#e5e7eb",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  achievementRow: {
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  achievementIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
  },
  achievementIconEarned: {
    backgroundColor: "#fef3c7",
  },
  achievementEmoji: {
    fontSize: 18,
  },
  achievementText: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  achievementTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  achievementTitle: {
    flex: 1,
    color: "#111111",
    fontSize: 14,
    fontWeight: "800",
  },
  achievementDetail: {
    color: "#666666",
    fontSize: 12,
    lineHeight: 17,
  },
  earnedText: {
    color: "#b45309",
    fontSize: 11,
    fontWeight: "800",
  },
  achievementProgressText: {
    color: "#666666",
    fontSize: 11,
    fontWeight: "800",
  },
  suggestionList: {
    gap: 10,
  },
  suggestionCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  suggestionIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  suggestionText: {
    flex: 1,
    minWidth: 0,
  },
  suggestionTitle: {
    color: "#111111",
    fontSize: 14,
    fontWeight: "800",
  },
  suggestionDetail: {
    color: "#555555",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  suggestionAction: {
    fontSize: 13,
    fontWeight: "800",
  },
  duaArabic: {
    color: "#111111",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 4,
    textAlign: "right",
  },
  quickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  quickAction: {
    flexBasis: "48%",
    flexGrow: 1,
    minHeight: 76,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  quickIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  quickText: {
    flex: 1,
    minWidth: 0,
  },
  quickTitle: {
    color: "#111111",
    fontSize: 13,
    fontWeight: "800",
  },
  quickDetail: {
    color: "#666666",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
});
