import { useCallback, useEffect, useMemo, useState, type ComponentProps, type ReactNode } from "react";
import {
  ActivityIndicator,
  Modal,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter, type Href } from "expo-router";
import { ChildBottomNav } from "@/src/components/child-bottom-nav";
import { ApiError, apiFetch } from "@/src/lib/api";
import { fetchReviewQueue, type ReviewQueueItem, type ReviewQueueResponse } from "@/src/lib/reviews";
import { getReviewPriorityStyle } from "@/src/lib/review-priority";

type WorkStatus = "not_started" | "in_progress" | "completed";
type IconName = ComponentProps<typeof Ionicons>["name"];

type DashboardChild = {
  id?: number;
  name: string;
  age?: number;
  avatarEmoji: string;
  streakDays: number;
  totalPoints: number;
  juzCompleted?: number;
  practiceMinutesPerDay?: number;
  hideStories?: boolean;
  hideDuas?: boolean;
};

type ChildDetail = DashboardChild & {
  readPagesPerDay: number;
};

type NewMemorization = {
  surahName: string;
  surahNumber: number;
  currentWorkSurahName?: string;
  currentWorkAyahStart?: number;
  currentWorkAyahEnd?: number;
  ayahStart: number;
  ayahEnd: number;
  pageStart: number;
  pageEnd: number;
  workLabel?: string;
  isReviewOnly?: boolean;
  estimatedMinutes?: number;
};

type DashboardStory = {
  id: number;
  title: string;
};

type DashboardDua = {
  id: number;
  arabic: string;
  transliteration: string;
  translation: string;
};

type DashboardReviewSession = {
  surahName: string;
  surahNumber: number;
  ayahCount: number;
};

type SwitcherChild = {
  id: number;
  name: string;
  age?: number;
  avatarEmoji: string;
};

type ChildrenResponse = {
  children: SwitcherChild[];
};

type Goal = {
  id: string;
  title: string;
  description: string;
  targetDate?: string;
  targetSurahCount?: number;
  currentCount?: number;
  type: string;
  autoGenerated?: boolean;
};

type Achievement = {
  id: string;
  title: string;
  description: string;
  icon: string;
  earned: boolean;
  earnedAt?: string | null;
  progress?: number | null;
  target?: number | null;
};

type MemorizationStats = {
  totalSurahsMemorized: number;
  totalVersesMemorized: number;
  juzCompleted: number;
  currentSurah: string | null;
  longestStreak: number;
  weeklyProgress: Array<{
    day: string;
    versesMemorized: number;
    minutesPracticed: number;
  }>;
};

type NextSurah = {
  number: number;
  nameArabic: string;
  nameTransliteration: string;
  nameTranslation: string;
  verseCount: number;
};

type TodayProgress = {
  memStatus: WorkStatus;
  reviewStatus: WorkStatus;
  reviewTargetCount: number | null;
  reviewCompletedCount: number;
};

type ReadingGoal = {
  targetPages: number;
  completedPages: number;
  lastPage: number | null;
  status: WorkStatus;
  isEnabled: boolean;
};

type DashboardResponse = {
  child: DashboardChild;
  todaysPlan: {
    newMemorization: NewMemorization | null;
    reviewSessions?: DashboardReviewSession[];
    story?: DashboardStory | null;
    dua?: DashboardDua | null;
    totalEstimatedMinutes: number;
  };
  memorizationStats?: MemorizationStats;
  recentSessions?: Array<unknown>;
  reviewsDueToday: number;
  nextSurah?: NextSurah | null;
  achievements?: Achievement[];
  goals?: Goal[];
  todayProgress?: TodayProgress;
  readingGoal: ReadingGoal | null;
  upNextMemorization?: NewMemorization | null;
};

type DashboardState =
  | { status: "loading" }
  | { status: "error"; message: string }
  | {
      status: "ok";
      dashboard: DashboardResponse;
      reviews: ReviewQueueResponse | null;
      reviewError: string | null;
      dashboardError: string | null;
    };

type CardTone = {
  accent: string;
  bg: string;
  border: string;
  soft: string;
};

type GoalsPanelTab = "goals" | "achievements";

const CARD_TONES: Record<"memorization" | "review" | "reading", CardTone> = {
  memorization: {
    accent: "#2563eb",
    bg: "#f8fbff",
    border: "#bfdbfe",
    soft: "#dbeafe",
  },
  review: {
    accent: "#ea580c",
    bg: "#fffaf5",
    border: "#fed7aa",
    soft: "#ffedd5",
  },
  reading: {
    accent: "#0f766e",
    bg: "#f5fffc",
    border: "#99f6e4",
    soft: "#ccfbf1",
  },
};

const STATUS_COPY: Record<WorkStatus, { label: string; color: string; bg: string; border: string }> = {
  not_started: {
    label: "Ready",
    color: "#2563eb",
    bg: "#eff6ff",
    border: "#bfdbfe",
  },
  in_progress: {
    label: "In progress",
    color: "#b45309",
    bg: "#fffbeb",
    border: "#fde68a",
  },
  completed: {
    label: "Complete",
    color: "#047857",
    bg: "#ecfdf5",
    border: "#a7f3d0",
  },
};

function formatAyahRange(start: number | undefined, end: number | undefined) {
  if (start == null || end == null) return "Ayahs";
  return start === end ? `Ayah ${start}` : `Ayahs ${start}-${end}`;
}

function formatPageRange(start: number | undefined, end: number | undefined) {
  if (start == null || end == null) return null;
  return start === end ? `Page ${start}` : `Pages ${start}-${end}`;
}

function formatPercent(value: number, target: number) {
  if (target <= 0) return 0;
  return Math.max(0, Math.min(100, Math.round((value / target) * 100)));
}

function formatGoalDate(value: string | undefined) {
  if (!value) return null;
  const date = new Date(`${value}T12:00:00`);
  if (Number.isNaN(date.getTime())) return null;
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

function getLocalDateValue() {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function parseLocalDate(value: string) {
  return new Date(`${value}T12:00:00`);
}

function formatLocalDateValue(date: Date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function addLocalDays(value: string, days: number) {
  const date = parseLocalDate(value);
  date.setDate(date.getDate() + days);
  return formatLocalDateValue(date);
}

function formatScrubberDate(value: string) {
  const date = parseLocalDate(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString(undefined, {
    weekday: "short",
    month: "short",
    day: "numeric",
  });
}

function getGoalPercent(goal: Goal) {
  return formatPercent(goal.currentCount ?? 0, goal.targetSurahCount ?? 0);
}

function getGoalTimestamp(goal: Goal) {
  if (!goal.targetDate) return null;
  const date = parseLocalDate(goal.targetDate);
  return Number.isNaN(date.getTime()) ? null : date.getTime();
}

function isGoalActive(goal: Goal) {
  const target = goal.targetSurahCount ?? 0;
  return target <= 0 || (goal.currentCount ?? 0) < target;
}

function pickUrgentGoal(goals: Goal[]) {
  if (goals.length === 0) return null;

  const activeGoals = goals.filter(isGoalActive);
  const pool = activeGoals.length > 0 ? activeGoals : goals;
  const datedGoals = pool.filter((goal) => getGoalTimestamp(goal) != null);

  if (datedGoals.length === 0) return pool[0] ?? null;

  return [...datedGoals].sort((a, b) => {
    return (getGoalTimestamp(a) ?? Number.MAX_SAFE_INTEGER) -
      (getGoalTimestamp(b) ?? Number.MAX_SAFE_INTEGER);
  })[0] ?? null;
}

function getGoalDaysLeft(goal: Goal) {
  if (!goal.targetDate) return null;
  const targetDate = parseLocalDate(goal.targetDate);
  const today = parseLocalDate(getLocalDateValue());
  if (Number.isNaN(targetDate.getTime()) || Number.isNaN(today.getTime())) return null;
  return Math.round((targetDate.getTime() - today.getTime()) / 86_400_000);
}

function formatDaysLeft(days: number | null) {
  if (days == null) return "No date";
  if (days === 0) return "Due today";
  if (days < 0) return `${Math.abs(days)} day${days === -1 ? "" : "s"} late`;
  return `${days} day${days === 1 ? "" : "s"} left`;
}

function getAchievementPercent(achievement: Achievement) {
  const progress = achievement.progress ?? 0;
  const target = achievement.target ?? 0;
  return achievement.earned ? 100 : target > 0 ? formatPercent(progress, target) : 0;
}

function getAchievementTimestamp(achievement: Achievement) {
  if (!achievement.earnedAt) return null;
  const date = new Date(achievement.earnedAt);
  return Number.isNaN(date.getTime()) ? null : date.getTime();
}

function pickDashboardAchievements(achievements: Achievement[]) {
  const earned = achievements
    .filter((achievement) => achievement.earned)
    .sort((a, b) => {
      return (getAchievementTimestamp(b) ?? 0) - (getAchievementTimestamp(a) ?? 0);
    })[0];
  const inProgress = achievements
    .filter((achievement) => !achievement.earned && (achievement.target ?? 0) > 0)
    .sort((a, b) => getAchievementPercent(b) - getAchievementPercent(a));

  return earned ? [earned, ...inProgress.slice(0, 2)] : inProgress.slice(0, 3);
}

function formatAge(age: number | undefined) {
  if (typeof age !== "number" || !Number.isFinite(age)) return "Age not set";
  return `${age} yr${age === 1 ? "" : "s"}`;
}

function wait(ms: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function describeError(error: unknown) {
  if (error instanceof ApiError) {
    return `${error.message} (${error.path}; cookie=${error.hasCookie ? "yes" : "no"})`;
  }
  if (error instanceof Error) {
    return error.message;
  }
  return "Unknown failure";
}

function fallbackChild(childId: string | undefined, name: string | undefined): ChildDetail {
  return {
    name: name || (childId ? `Child ${childId}` : "Child"),
    avatarEmoji: "?",
    streakDays: 0,
    totalPoints: 0,
    readPagesPerDay: 0,
  };
}

function isValidChildId(childId: string | undefined) {
  return typeof childId === "string" && /^\d+$/.test(childId);
}

function fallbackDashboard(
  child: ChildDetail,
  reviews: ReviewQueueResponse | null,
): DashboardResponse {
  const reviewCount = reviews?.dueToday.length ?? 0;
  const readPagesPerDay = child.readPagesPerDay ?? 0;

  return {
    child: {
      name: child.name,
      avatarEmoji: child.avatarEmoji,
      streakDays: child.streakDays,
      totalPoints: child.totalPoints,
    },
    todaysPlan: {
      newMemorization: null,
      totalEstimatedMinutes: 0,
    },
    reviewsDueToday: reviewCount,
    todayProgress: {
      memStatus: "not_started",
      reviewStatus: "not_started",
      reviewTargetCount: reviewCount,
      reviewCompletedCount: 0,
    },
    readingGoal: {
      targetPages: readPagesPerDay,
      completedPages: 0,
      lastPage: null,
      status: "not_started",
      isEnabled: readPagesPerDay > 0,
    },
  };
}

function WorkCard({
  title,
  eyebrow,
  detail,
  cta,
  tone,
  onPress,
  readOnly = false,
  onReadOnlyPress,
  status,
  children,
}: {
  title: string;
  eyebrow: string;
  detail: string;
  cta: string;
  tone: CardTone;
  onPress: () => void;
  readOnly?: boolean;
  onReadOnlyPress?: () => void;
  status?: WorkStatus;
  children?: ReactNode;
}) {
  const statusStyle = status ? STATUS_COPY[status] : null;

  return (
    <Pressable
      style={[
        styles.card,
        {
          backgroundColor: tone.bg,
          borderColor: tone.border,
        },
        readOnly && styles.cardReadOnly,
      ]}
      onPress={readOnly ? onReadOnlyPress : onPress}
      accessibilityState={readOnly ? { disabled: true } : undefined}
    >
      <View style={styles.cardHeader}>
        <View style={[styles.cardIcon, { backgroundColor: tone.soft }]}>
          <Text style={[styles.cardIconText, { color: tone.accent }]}>
            {title.charAt(0)}
          </Text>
        </View>
        <View style={styles.cardTitleBlock}>
          <Text style={styles.cardEyebrow}>{eyebrow}</Text>
          <Text style={styles.cardLabel}>{title}</Text>
        </View>
        {statusStyle && (
          <View
            style={[
              styles.statusPill,
              {
                backgroundColor: statusStyle.bg,
                borderColor: statusStyle.border,
              },
            ]}
          >
            <Text style={[styles.statusPillText, { color: statusStyle.color }]}>
              {statusStyle.label}
            </Text>
          </View>
        )}
        <Text style={[styles.cardAction, { color: readOnly ? "#94a3b8" : tone.accent }]}>
          {cta}
        </Text>
      </View>
      <Text style={styles.cardDetail}>{detail}</Text>
      {children}
    </Pressable>
  );
}

function SectionHeader({
  title,
  action,
  onPress,
}: {
  title: string;
  action?: string;
  onPress?: () => void;
}) {
  return (
    <View style={styles.sectionHeader}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {action && onPress ? (
        <Pressable onPress={onPress}>
          <Text style={styles.sectionAction}>{action}</Text>
        </Pressable>
      ) : null}
    </View>
  );
}

function PrimarySectionHeader({ title }: { title: string }) {
  return (
    <View style={styles.primarySectionHeader}>
      <Text style={styles.primarySectionTitle}>{title}</Text>
    </View>
  );
}

function ProgressBar({
  value,
  color,
}: {
  value: number;
  color: string;
}) {
  return (
    <View style={styles.progressTrack}>
      <View style={[styles.progressFill, { width: `${value}%`, backgroundColor: color }]} />
    </View>
  );
}

function AchievementPreview({ achievement }: { achievement: Achievement }) {
  const progress = achievement.progress ?? 0;
  const target = achievement.target ?? 0;
  const percent = achievement.earned ? 100 : target > 0 ? formatPercent(progress, target) : 0;

  return (
    <View style={styles.achievementRow}>
      <View style={[styles.achievementIcon, achievement.earned && styles.achievementIconEarned]}>
        <Text style={styles.achievementEmoji}>{achievement.icon}</Text>
      </View>
      <View style={styles.achievementText}>
        <View style={styles.achievementTitleRow}>
          <Text style={styles.achievementTitle}>{achievement.title}</Text>
          {achievement.earned ? (
            <Text style={styles.earnedText}>Earned</Text>
          ) : target > 0 ? (
            <Text style={styles.achievementProgressText}>
              {progress}/{target}
            </Text>
          ) : null}
        </View>
        <Text style={styles.achievementDetail}>{achievement.description}</Text>
        {!achievement.earned && target > 0 ? (
          <ProgressBar value={percent} color="#f59e0b" />
        ) : null}
      </View>
    </View>
  );
}

function CompactSuggestionCard({
  title,
  detail,
  iconName,
  color,
  onPress,
  children,
}: {
  title: string;
  detail: string;
  iconName: IconName;
  color: string;
  onPress: () => void;
  children?: ReactNode;
}) {
  return (
    <Pressable
      style={[styles.compactSuggestionCard, { borderColor: `${color}33`, backgroundColor: `${color}0d` }]}
      onPress={onPress}
    >
      <View style={[styles.compactSuggestionIcon, { backgroundColor: `${color}18` }]}>
        <Ionicons name={iconName} size={16} color={color} />
      </View>
      <View style={styles.compactSuggestionText}>
        <Text style={styles.compactSuggestionTitle} numberOfLines={1}>
          {title}
        </Text>
        <Text style={styles.compactSuggestionDetail} numberOfLines={1}>
          {detail}
        </Text>
        {children}
      </View>
    </Pressable>
  );
}

function GoalFocus({ goal }: { goal: Goal | null }) {
  if (!goal) {
    return (
      <View style={styles.combinedEmpty}>
        <Text style={styles.combinedEmptyText}>No active goals yet.</Text>
      </View>
    );
  }

  const current = goal.currentCount ?? 0;
  const target = goal.targetSurahCount ?? 0;
  const percent = getGoalPercent(goal);
  const dateLabel = formatGoalDate(goal.targetDate);
  const daysLeft = getGoalDaysLeft(goal);

  return (
    <View style={styles.goalFocus}>
      <View style={styles.goalFocusHeader}>
        <Text style={styles.goalFocusTitle} numberOfLines={2}>
          {goal.title}
        </Text>
        <View style={styles.daysBadge}>
          <Text style={styles.daysBadgeText}>{formatDaysLeft(daysLeft)}</Text>
        </View>
      </View>
      <Text style={styles.goalFocusDetail} numberOfLines={2}>
        {goal.description}
      </Text>
      <View style={styles.goalFocusProgressHeader}>
        <Text style={styles.goalFocusMeta}>
          {target > 0 ? `${current}/${target} surahs` : "Progress"}
        </Text>
        <Text style={styles.goalFocusPercent}>{percent}%</Text>
      </View>
      <ProgressBar value={percent} color="#2563eb" />
      <View style={styles.goalFocusDateRow}>
        <Ionicons name="calendar-outline" size={14} color="#64748b" />
        <Text style={styles.goalFocusDateText}>
          {dateLabel ? `Target ${dateLabel}` : "No target date set"}
        </Text>
      </View>
    </View>
  );
}

function GoalsAchievementsCard({
  activeTab,
  onTabChange,
  goal,
  achievements,
  onOpenGoals,
  onOpenAchievements,
}: {
  activeTab: GoalsPanelTab;
  onTabChange: (tab: GoalsPanelTab) => void;
  goal: Goal | null;
  achievements: Achievement[];
  onOpenGoals: () => void;
  onOpenAchievements: () => void;
}) {
  return (
    <View style={styles.combinedCard}>
      <View style={styles.combinedTabs}>
        {(["goals", "achievements"] as const).map((tab) => {
          const selected = activeTab === tab;
          return (
            <Pressable
              key={tab}
              style={[styles.combinedTab, selected && styles.combinedTabActive]}
              onPress={() => onTabChange(tab)}
            >
              <Text style={[styles.combinedTabText, selected && styles.combinedTabTextActive]}>
                {tab === "goals" ? "Goals" : "Achievements"}
              </Text>
            </Pressable>
          );
        })}
      </View>

      {activeTab === "goals" ? (
        <View style={styles.combinedBody}>
          <GoalFocus goal={goal} />
          <Pressable style={styles.combinedLinkRow} onPress={onOpenGoals}>
            <Text style={styles.combinedLinkText}>View all goals →</Text>
          </Pressable>
        </View>
      ) : (
        <View style={styles.combinedBody}>
          {achievements.length > 0 ? (
            <View style={styles.combinedRows}>
              {achievements.map((achievement) => (
                <AchievementPreview key={achievement.id} achievement={achievement} />
              ))}
            </View>
          ) : (
            <View style={styles.combinedEmpty}>
              <Text style={styles.combinedEmptyText}>No achievements in progress yet.</Text>
            </View>
          )}
          <Pressable style={styles.combinedLinkRow} onPress={onOpenAchievements}>
            <Text style={styles.combinedLinkText}>View all →</Text>
          </Pressable>
        </View>
      )}
    </View>
  );
}

function QuickAction({
  title,
  detail,
  iconName,
  color,
  onPress,
}: {
  title: string;
  detail: string;
  iconName: IconName;
  color: string;
  onPress: () => void;
}) {
  return (
    <Pressable style={styles.quickAction} onPress={onPress}>
      <View style={[styles.quickIcon, { backgroundColor: `${color}14` }]}>
        <Ionicons name={iconName} size={18} color={color} />
      </View>
      <View style={styles.quickText}>
        <Text style={styles.quickTitle} numberOfLines={1}>{title}</Text>
        <Text style={styles.quickDetail} numberOfLines={1}>{detail}</Text>
      </View>
    </Pressable>
  );
}

function ReviewPreviewItem({ item }: { item: ReviewQueueItem }) {
  const priorityStyle = getReviewPriorityStyle(item.reviewPriority);
  const rangeLabel = formatAyahRange(item.ayahStart, item.ayahEnd);

  return (
    <View
      style={[
        styles.reviewPreview,
        {
          backgroundColor: priorityStyle.cardBg,
          borderColor: priorityStyle.border,
        },
      ]}
    >
      <View style={[styles.reviewDot, { backgroundColor: priorityStyle.text }]} />
      <View style={styles.reviewPreviewText}>
        <Text style={styles.reviewSurah} numberOfLines={1}>
          {item.surahName ?? `Surah ${item.surahNumber}`}
        </Text>
        <Text style={styles.reviewRange}>{rangeLabel}</Text>
      </View>
      <Text style={[styles.reviewPriority, { color: priorityStyle.text }]}>
        {priorityStyle.label}
      </Text>
    </View>
  );
}

function PlannedReviewPreviewItem({ item }: { item: DashboardReviewSession }) {
  return (
    <View
      style={[
        styles.reviewPreview,
        { backgroundColor: "#fffaf5", borderColor: "#fed7aa" },
      ]}
    >
      <View style={[styles.reviewDot, { backgroundColor: "#ea580c" }]} />
      <View style={styles.reviewPreviewText}>
        <Text style={styles.reviewSurah} numberOfLines={1}>
          {item.surahName}
        </Text>
        <Text style={styles.reviewRange}>
          {item.ayahCount} ayah{item.ayahCount === 1 ? "" : "s"}
        </Text>
      </View>
      <Text style={[styles.reviewPriority, { color: "#ea580c" }]}>
        Review
      </Text>
    </View>
  );
}

function ChildSwitcherSheet({
  visible,
  childrenList,
  currentChildId,
  loading,
  error,
  fallbackChild,
  onClose,
  onRetry,
  onSwitch,
  onAddChild,
}: {
  visible: boolean;
  childrenList: SwitcherChild[];
  currentChildId: number;
  loading: boolean;
  error: string | null;
  fallbackChild: { name: string; avatarEmoji: string; age?: number };
  onClose: () => void;
  onRetry: () => void;
  onSwitch: (child: SwitcherChild) => void;
  onAddChild: () => void;
}) {
  const fallbackSwitcherChild: SwitcherChild | null = Number.isFinite(currentChildId)
    ? {
        id: currentChildId,
        name: fallbackChild.name,
        avatarEmoji: fallbackChild.avatarEmoji,
        age: fallbackChild.age,
      }
    : null;
  const sheetChildren = fallbackSwitcherChild &&
    !childrenList.some((child) => child.id === currentChildId)
    ? [fallbackSwitcherChild, ...childrenList]
    : childrenList;

  return (
    <Modal
      visible={visible}
      transparent
      animationType="slide"
      onRequestClose={onClose}
    >
      <Pressable style={styles.sheetBackdrop} onPress={onClose}>
        <Pressable style={styles.switcherSheet} onPress={(event) => event.stopPropagation()}>
          <View style={styles.sheetHandle} />
          <View style={styles.switcherHeader}>
            <View>
              <Text style={styles.sheetTitle}>Switch child</Text>
              <Text style={styles.sheetSubtitle}>Choose another dashboard</Text>
            </View>
            <Pressable
              accessibilityRole="button"
              accessibilityLabel="Close child switcher"
              hitSlop={8}
              style={styles.sheetCloseButton}
              onPress={onClose}
            >
              <Ionicons name="close" size={19} color="#64748b" />
            </Pressable>
          </View>

          {loading && sheetChildren.length === 0 ? (
            <View style={styles.switcherState}>
              <ActivityIndicator size="small" color="#2563eb" />
              <Text style={styles.switcherStateText}>Loading profiles</Text>
            </View>
          ) : error && sheetChildren.length === 0 ? (
            <View style={styles.switcherState}>
              <Text style={styles.switcherErrorText}>{error}</Text>
              <Pressable style={styles.switcherRetryButton} onPress={onRetry}>
                <Text style={styles.switcherRetryText}>Retry</Text>
              </Pressable>
            </View>
          ) : (
            <ScrollView style={styles.switcherList} contentContainerStyle={styles.switcherListContent}>
              {error ? (
                <View style={styles.switcherInlineWarning}>
                  <Text style={styles.switcherInlineWarningText}>{error}</Text>
                </View>
              ) : null}
              {sheetChildren.map((child) => {
                const selected = child.id === currentChildId;
                return (
                  <Pressable
                    key={child.id}
                    style={[styles.switcherRow, selected && styles.switcherRowSelected]}
                    onPress={() => {
                      if (selected) {
                        onClose();
                      } else {
                        onSwitch(child);
                      }
                    }}
                  >
                    <View style={styles.switcherAvatar}>
                      <Text style={styles.switcherAvatarText}>{child.avatarEmoji}</Text>
                    </View>
                    <View style={styles.switcherText}>
                      <Text style={styles.switcherName} numberOfLines={1}>
                        {child.name}
                      </Text>
                      <Text style={styles.switcherMeta}>{formatAge(child.age)}</Text>
                    </View>
                    {selected ? (
                      <View style={styles.switcherSelectedBadge}>
                        <Ionicons name="checkmark" size={14} color="#047857" />
                      </View>
                    ) : (
                      <View style={styles.switcherAction}>
                        <Text style={styles.switcherActionText}>Switch</Text>
                        <Ionicons name="chevron-forward" size={15} color="#64748b" />
                      </View>
                    )}
                  </Pressable>
                );
              })}
            </ScrollView>
          )}

          <Pressable style={styles.addChildRow} onPress={onAddChild}>
            <View style={styles.addChildIcon}>
              <Ionicons name="add" size={18} color="#2563eb" />
            </View>
            <Text style={styles.addChildText}>Add Child</Text>
          </Pressable>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

export default function ChildDashboard() {
  const { childId, name } = useLocalSearchParams<{ childId: string; name: string }>();
  const router = useRouter();
  const [state, setState] = useState<DashboardState>({ status: "loading" });
  const [refreshing, setRefreshing] = useState(false);
  const [selectedDate, setSelectedDate] = useState(() => getLocalDateValue());
  const [switcherOpen, setSwitcherOpen] = useState(false);
  const [switcherChildren, setSwitcherChildren] = useState<SwitcherChild[] | null>(null);
  const [switcherError, setSwitcherError] = useState<string | null>(null);
  const [switcherLoading, setSwitcherLoading] = useState(false);
  const [readOnlyNotice, setReadOnlyNotice] = useState<string | null>(null);
  const [goalsPanelTab, setGoalsPanelTab] = useState<GoalsPanelTab>("goals");
  const navChildId = typeof childId === "string" ? childId : undefined;
  const navName = typeof name === "string" ? name : "";
  const todayDate = getLocalDateValue();
  const isViewingToday = selectedDate === todayDate;
  const dateLabel = formatScrubberDate(selectedDate);
  const navReviewCount =
    state.status === "ok"
      ? state.reviews?.dueToday.length ?? state.dashboard.reviewsDueToday
      : undefined;
  const headerChild = state.status === "ok"
    ? state.dashboard.child
    : { name: navName || "Dashboard", avatarEmoji: "?", age: undefined };
  const sortedSwitcherChildren = useMemo(() => {
    const list = [...(switcherChildren ?? [])];
    const currentId = Number(childId);

    return list.sort((a, b) => {
      if (a.id === currentId) return -1;
      if (b.id === currentId) return 1;
      return a.name.localeCompare(b.name, undefined, { sensitivity: "base" });
    });
  }, [childId, switcherChildren]);

  const loadDashboard = useCallback(
    async (mode: "initial" | "refresh" = "initial") => {
      const childIdParam = childId;
      const nameParam = name;
      const dashboardPath = `/api/children/${childIdParam}/dashboard${
        isViewingToday ? "" : "?preview=true"
      }`;
      const requestOptions = isViewingToday
        ? undefined
        : { headers: { "x-local-date": selectedDate } };

      if (mode === "initial") {
        setState({ status: "loading" });
      } else {
        setRefreshing(true);
      }

      if (!isValidChildId(childIdParam)) {
        setState({
          status: "error",
          message: "This dashboard route is missing a valid child id. Go back and reopen the child profile.",
        });
        setRefreshing(false);
        return;
      }

      try {
        let dashboard: DashboardResponse;
        try {
          dashboard = await apiFetch<DashboardResponse>(
            dashboardPath,
            requestOptions,
          );
        } catch {
          await wait(350);
          dashboard = await apiFetch<DashboardResponse>(
            dashboardPath,
            requestOptions,
          );
        }
        let reviews: ReviewQueueResponse | null = null;
        let reviewError: string | null = null;

        if (isViewingToday) {
          try {
            reviews = await fetchReviewQueue(childIdParam);
          } catch (e) {
            reviewError = describeError(e);
          }
        }

        setState({
          status: "ok",
          dashboard,
          reviews,
          reviewError,
          dashboardError: null,
        });
      } catch (e) {
        const dashboardError = describeError(e);
        let reviews: ReviewQueueResponse | null = null;
        let reviewError: string | null = null;
        let child: ChildDetail | null = null;

        if (isViewingToday) {
          try {
            reviews = await fetchReviewQueue(childIdParam);
          } catch (reviewFetchError) {
            reviewError = describeError(reviewFetchError);
          }
        }

        try {
          child = await apiFetch<ChildDetail>(`/api/children/${childIdParam}`);
        } catch {
          child = fallbackChild(childIdParam, nameParam);
        }

        setState({
          status: "ok",
          dashboard: fallbackDashboard(child, reviews),
          reviews,
          reviewError,
          dashboardError,
        });
      } finally {
        setRefreshing(false);
      }
    },
    [childId, isViewingToday, name, selectedDate],
  );

  const loadSwitcherChildren = useCallback(async () => {
    setSwitcherLoading(true);
    setSwitcherError(null);
    try {
      const data = await apiFetch<ChildrenResponse>("/api/children");
      setSwitcherChildren(data.children);
    } catch (e) {
      setSwitcherError(e instanceof Error ? e.message : "Failed to load profiles.");
    } finally {
      setSwitcherLoading(false);
    }
  }, []);

  useEffect(() => {
    setReadOnlyNotice(null);
  }, [selectedDate]);

  useEffect(() => {
    if (!readOnlyNotice) return undefined;

    const timer = setTimeout(() => {
      setReadOnlyNotice(null);
    }, 3200);

    return () => clearTimeout(timer);
  }, [readOnlyNotice]);

  useFocusEffect(
    useCallback(() => {
      loadDashboard();
    }, [loadDashboard]),
  );

  function showReadOnlyNotice() {
    setReadOnlyNotice(`Viewing ${formatScrubberDate(selectedDate)}. Switch to Today to start work.`);
  }

  function shiftSelectedDate(days: number) {
    setSelectedDate((current) => addLocalDays(current, days));
  }

  function resetToToday() {
    setSelectedDate(getLocalDateValue());
  }

  function openChildSwitcher() {
    setSwitcherOpen(true);
    void loadSwitcherChildren();
  }

  function switchChild(child: SwitcherChild) {
    setSwitcherOpen(false);
    router.replace({
      pathname: "/child/[childId]",
      params: { childId: String(child.id), name: child.name },
    });
  }

  function addChildFromSwitcher() {
    setSwitcherOpen(false);
    router.push("/profile/new");
  }

  function handleCardPress(key: string) {
    if (!isViewingToday) {
      showReadOnlyNotice();
      return;
    }

    if (key === "review") {
      router.push({
        pathname: "/child/[childId]/review",
        params: { childId, name: name ?? "" },
      });
    } else if (key === "reading") {
      router.push({
        pathname: "/child/[childId]/mushaf",
        params: { childId, name: name ?? "" },
      });
    } else if (key === "memorization") {
      router.push({
        pathname: "/child/[childId]/memorization",
        params: { childId, name: name ?? "" },
      });
    }
  }

  function handleTargetsPress() {
    if (!isValidChildId(childId)) return;

    router.push({
      pathname: "/child/[childId]/targets",
      params: { childId, name: name ?? "" },
    });
  }

  function openChildRoute(
    pathname:
      | "/child/[childId]/memorization"
      | "/child/[childId]/review"
      | "/child/[childId]/mushaf"
      | "/child/[childId]/targets"
      | "/child/[childId]/profile"
      | "/child/[childId]/more",
    displayName = name ?? "",
  ) {
    if (!isValidChildId(childId)) return;
    router.push({
      pathname,
      params: { childId, name: displayName },
    });
  }

  function openFutureChildRoute(segment: "plan" | "progress", displayName = name ?? "") {
    if (!isValidChildId(childId)) return;
    const nameQuery = displayName ? `?name=${encodeURIComponent(displayName)}` : "";
    router.push(`/child/${childId}/${segment}${nameQuery}` as Href);
  }

  function renderContent() {
    if (state.status === "loading") {
      return (
        <View style={styles.center}>
          <ActivityIndicator size="large" color="#2563eb" />
        </View>
      );
    }

    if (state.status === "error") {
      return (
        <View style={styles.center}>
          <Text style={styles.errorText}>{state.message}</Text>
          <Pressable style={styles.retryButton} onPress={() => loadDashboard()}>
            <Text style={styles.retryText}>Retry</Text>
          </Pressable>
        </View>
      );
    }

    const { dashboard, reviews, reviewError, dashboardError } = state;
    const child = dashboard.child;
    const todaysMem = dashboard.todaysPlan.newMemorization;
    const stats = dashboard.memorizationStats;
    const goals = dashboard.goals ?? [];
    const achievements = dashboard.achievements ?? [];
    const urgentGoal = pickUrgentGoal(goals);
    const dashboardAchievements = pickDashboardAchievements(achievements);
    const todayProgress = dashboard.todayProgress;
    const dayCopy = isViewingToday ? "today" : "this day";
    const memStatus = todayProgress?.memStatus ?? "not_started";
    const memSurah = todaysMem?.currentWorkSurahName ?? todaysMem?.surahName;
    const memAyahStart = todaysMem?.currentWorkAyahStart ?? todaysMem?.ayahStart;
    const memAyahEnd = todaysMem?.currentWorkAyahEnd ?? todaysMem?.ayahEnd;
    const memPageLabel = formatPageRange(todaysMem?.pageStart, todaysMem?.pageEnd);
    const memDetail = !todaysMem
      ? stats?.totalSurahsMemorized
        ? `No new memorization assigned for ${dayCopy}. Keep the memory fresh with review or reading.`
        : `No memorization assigned for ${dayCopy}.`
      : memStatus === "completed"
      ? `${todaysMem.workLabel ?? "Memorization"} complete for ${todaysMem.surahName}.`
      : memStatus === "in_progress"
      ? `${memSurah} is in progress · ${formatAyahRange(memAyahStart, memAyahEnd)}${
          memPageLabel ? ` · ${memPageLabel}` : ""
        }`
      : `${todaysMem.workLabel ?? "New Memorization"} · ${memSurah} · ${formatAyahRange(
          memAyahStart,
          memAyahEnd,
        )}${memPageLabel ? ` · ${memPageLabel}` : ""}`;
    const memCta = !isViewingToday
      ? memStatus === "completed" ? "Done" : "View only"
      : memStatus === "completed" ? "Done" : memStatus === "in_progress" ? "Continue" : "Start";

    const dueItems = isViewingToday ? reviews?.dueToday ?? [] : [];
    const reviewedItems = isViewingToday ? reviews?.reviewedToday ?? [] : [];
    const plannedReviewSessions = !isViewingToday ? dashboard.todaysPlan.reviewSessions ?? [] : [];
    const reviewsDueToday = reviews ? dueItems.length : dashboard.reviewsDueToday;
    const reviewCompletedToday = Math.max(
      todayProgress?.reviewCompletedCount ?? 0,
      reviewedItems.length,
    );
    const reviewTarget =
      todayProgress?.reviewTargetCount != null
        ? Math.max(todayProgress.reviewTargetCount, reviewCompletedToday)
        : reviewsDueToday + reviewCompletedToday;
    const reviewDone =
      todayProgress?.reviewStatus === "completed" ||
      (reviewsDueToday === 0 && reviewCompletedToday > 0);
    const reviewStatusForCard: WorkStatus = reviewDone
      ? "completed"
      : reviewCompletedToday > 0
      ? "in_progress"
      : "not_started";
    const hasReviewActivity =
      reviewsDueToday > 0 ||
      reviewCompletedToday > 0 ||
      todayProgress?.reviewStatus === "in_progress";
    const reviewDetail = reviewDone
      ? `Review complete · ${reviewCompletedToday}/${Math.max(
          reviewTarget,
          reviewCompletedToday,
        )} done`
      : reviewsDueToday > 0
      ? `${reviewsDueToday} review${reviewsDueToday === 1 ? "" : "s"} due for ${dayCopy}${
          reviewCompletedToday > 0 ? ` · ${reviewCompletedToday} done` : ""
        }`
      : reviewError
      ? "Review queue could not refresh."
      : "Review is clear today. A light read still counts toward the habit.";
    const reviewCta = !isViewingToday
      ? reviewDone ? "Done" : "View only"
      : reviewDone ? "Done" : reviewsDueToday > 0 ? "Review" : "Open";

    const readingGoal = dashboard.readingGoal;
    const readingEnabled = !!readingGoal?.isEnabled;
    const readingDetail = !readingEnabled
      ? "No reading goal set yet. Add one from Targets when reading is part of the day."
      : readingGoal.status === "completed"
      ? `Reading complete · ${readingGoal.completedPages}/${readingGoal.targetPages} pages`
      : readingGoal.status === "in_progress"
      ? `${readingGoal.completedPages}/${readingGoal.targetPages} pages read · resume page ${
          readingGoal.lastPage ?? 1
        }`
      : `Read ${readingGoal.targetPages} page${
          readingGoal.targetPages === 1 ? "" : "s"
        } for ${dayCopy}${readingGoal.lastPage ? ` · saved page ${readingGoal.lastPage}` : ""}`;
    const readingCta = !isViewingToday
      ? readingGoal?.status === "completed" ? "Done" : "View only"
      : readingGoal?.status === "completed"
        ? "Done"
        : readingGoal?.status === "in_progress"
        ? "Resume"
        : "Read";
    const readingStatus = readingGoal?.status ?? "not_started";
    const story = !child.hideStories ? dashboard.todaysPlan.story : null;
    const dua = !child.hideDuas ? dashboard.todaysPlan.dua : null;
    const hasContentSuggestions = !!story || !!dua;
    const upNextMem = dashboard.upNextMemorization;
    const nextWorkTitle = upNextMem
      ? upNextMem.workLabel ?? "Next Memorization"
      : dashboard.nextSurah
      ? "Next Surah"
      : null;
    const nextWorkDetail = upNextMem
      ? `${upNextMem.surahName} · ${formatAyahRange(upNextMem.ayahStart, upNextMem.ayahEnd)}${
          formatPageRange(upNextMem.pageStart, upNextMem.pageEnd)
            ? ` · ${formatPageRange(upNextMem.pageStart, upNextMem.pageEnd)}`
            : ""
        }`
      : dashboard.nextSurah
      ? `${dashboard.nextSurah.nameTransliteration} · ${dashboard.nextSurah.nameTranslation} · ${dashboard.nextSurah.verseCount} verses`
      : null;
    const allPrimaryWorkComplete =
      (!todaysMem || memStatus === "completed") &&
      (reviewDone || reviewsDueToday === 0) &&
      (!readingEnabled || readingGoal?.status === "completed");
    const noPrimaryWork =
      !todaysMem &&
      reviewsDueToday === 0 &&
      reviewCompletedToday === 0 &&
      !readingEnabled;
    const showCompleteBanner = allPrimaryWorkComplete && !noPrimaryWork;

    return (
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.list}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={() => loadDashboard("refresh")}
            tintColor="#2563eb"
          />
        }
      >
        {dashboardError && (
          <View style={styles.warningBanner}>
            <Text style={styles.warningText}>
              This plan is temporarily unavailable. Pull down to refresh shortly.
            </Text>
          </View>
        )}

        {readOnlyNotice && (
          <View style={styles.readOnlyBanner}>
            <Ionicons name="information-circle-outline" size={17} color="#475569" />
            <Text style={styles.readOnlyBannerText}>{readOnlyNotice}</Text>
          </View>
        )}

        {(showCompleteBanner || noPrimaryWork) && (
          <View
            style={[
              styles.dayStateBanner,
              showCompleteBanner ? styles.dayStateComplete : styles.dayStateEmpty,
            ]}
          >
            <Ionicons
              name={showCompleteBanner ? "checkmark-circle-outline" : "leaf-outline"}
              size={19}
              color={showCompleteBanner ? "#047857" : "#0f766e"}
            />
            <Text
              style={[
                styles.dayStateText,
                { color: showCompleteBanner ? "#047857" : "#0f766e" },
              ]}
            >
              {showCompleteBanner
                ? `All core work is complete for ${dayCopy}.`
                : "No required work is queued. Choose a light review, reading, or target update."}
            </Text>
          </View>
        )}

        <PrimarySectionHeader title={isViewingToday ? "Today's Work" : "Planned Work"} />

        <WorkCard
          title="Memorization"
          eyebrow={todaysMem?.isReviewOnly ? "Recitation focus" : "Today's work"}
          detail={memDetail}
          cta={memCta}
          tone={CARD_TONES.memorization}
          onPress={() => handleCardPress("memorization")}
          readOnly={!isViewingToday}
          onReadOnlyPress={showReadOnlyNotice}
          status={todaysMem ? memStatus : undefined}
        />

        <WorkCard
          title="Review"
          eyebrow="Review queue"
          detail={reviewDetail}
          cta={reviewCta}
          tone={CARD_TONES.review}
          onPress={() => handleCardPress("review")}
          readOnly={!isViewingToday}
          onReadOnlyPress={showReadOnlyNotice}
          status={hasReviewActivity ? reviewStatusForCard : undefined}
        >
          {dueItems.length > 0 && (
            <View style={styles.reviewPreviewList}>
              {dueItems.slice(0, 3).map((item) => (
                <ReviewPreviewItem key={item.id} item={item} />
              ))}
              {dueItems.length > 3 && (
                <Text style={styles.moreText}>+{dueItems.length - 3} more queued</Text>
              )}
            </View>
          )}
          {plannedReviewSessions.length > 0 && (
            <View style={styles.reviewPreviewList}>
              {plannedReviewSessions.slice(0, 3).map((item) => (
                <PlannedReviewPreviewItem
                  key={`${item.surahNumber}-${item.ayahCount}`}
                  item={item}
                />
              ))}
              {plannedReviewSessions.length > 3 && (
                <Text style={styles.moreText}>+{plannedReviewSessions.length - 3} more queued</Text>
              )}
            </View>
          )}
        </WorkCard>

        <WorkCard
          title="Reading"
          eyebrow="Mushaf"
          detail={readingDetail}
          cta={readingCta}
          tone={CARD_TONES.reading}
          onPress={() => handleCardPress("reading")}
          readOnly={!isViewingToday}
          onReadOnlyPress={showReadOnlyNotice}
          status={readingEnabled ? readingStatus : undefined}
        />

        {hasContentSuggestions && (
          <View style={styles.contentPair}>
            {story && (
              <CompactSuggestionCard
                title="Story"
                detail={story.title}
                iconName="sparkles-outline"
                color="#2563eb"
                onPress={() => openChildRoute("/child/[childId]/more", child.name)}
              />
            )}
            {dua && (
              <CompactSuggestionCard
                title="Du'a"
                detail={dua.translation}
                iconName="heart-outline"
                color="#be123c"
                onPress={() => openChildRoute("/child/[childId]/more", child.name)}
              />
            )}
          </View>
        )}

        {nextWorkTitle && nextWorkDetail && (
          <>
            <SectionHeader title="Up Next" />
            <Pressable
              style={[styles.nextCard, !isViewingToday && styles.nextCardReadOnly]}
              onPress={isViewingToday ? () => handleCardPress("memorization") : showReadOnlyNotice}
            >
              <View style={styles.nextNumber}>
                <Text style={styles.nextNumberText}>
                  {upNextMem?.surahNumber ?? dashboard.nextSurah?.number}
                </Text>
              </View>
              <View style={styles.nextText}>
                <Text style={styles.nextTitle}>{nextWorkTitle}</Text>
                <Text style={styles.nextDetail}>{nextWorkDetail}</Text>
              </View>
              {dashboard.nextSurah && !upNextMem ? (
                <Text style={styles.nextArabic}>{dashboard.nextSurah.nameArabic}</Text>
              ) : (
                <Ionicons name="chevron-forward" size={18} color="#2563eb" />
              )}
            </Pressable>
          </>
        )}

        <GoalsAchievementsCard
          activeTab={goalsPanelTab}
          onTabChange={setGoalsPanelTab}
          goal={urgentGoal}
          achievements={dashboardAchievements}
          onOpenGoals={() => openFutureChildRoute("plan", child.name)}
          onOpenAchievements={() => openFutureChildRoute("progress", child.name)}
        />

        <SectionHeader title="Quick Actions" />
        <View style={styles.quickGrid}>
          <QuickAction
            title="Plan"
            detail="Goals"
            iconName="map-outline"
            color="#2563eb"
            onPress={() => openFutureChildRoute("plan", child.name)}
          />
          <QuickAction
            title="Progress"
            detail="Stats"
            iconName="bar-chart-outline"
            color="#16a34a"
            onPress={() => openFutureChildRoute("progress", child.name)}
          />
          <QuickAction
            title="More"
            detail="All tools"
            iconName="grid-outline"
            color="#7c3aed"
            onPress={() => openChildRoute("/child/[childId]/more", child.name)}
          />
        </View>
      </ScrollView>
    );
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Go back"
          hitSlop={8}
          style={styles.headerIconButton}
          onPress={() => router.back()}
        >
          <Ionicons name="chevron-back" size={22} color="#111827" />
        </Pressable>

        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Switch child"
          style={styles.childSwitcherButton}
          onPress={openChildSwitcher}
        >
          <Text style={styles.headerAvatar}>{headerChild.avatarEmoji}</Text>
          <Text style={styles.headerChildName} numberOfLines={1}>
            {headerChild.name}
          </Text>
          <Ionicons name="chevron-down" size={15} color="#64748b" />
        </Pressable>

        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Open child settings"
          hitSlop={8}
          style={styles.headerIconButton}
          onPress={handleTargetsPress}
        >
          <Ionicons name="settings-outline" size={21} color="#111827" />
        </Pressable>
      </View>

      <View style={styles.dateBar}>
        <View style={styles.dateSide}>
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Previous day"
            hitSlop={8}
            style={styles.dateArrow}
            onPress={() => shiftSelectedDate(-1)}
          >
            <Ionicons name="chevron-back" size={18} color="#111827" />
          </Pressable>
        </View>

        <View style={styles.dateCenter}>
          <Text style={styles.dateLabel}>{dateLabel}</Text>
          {!isViewingToday && (
            <Pressable
              accessibilityRole="button"
              accessibilityLabel="Reset dashboard date to today"
              style={styles.todayResetButton}
              onPress={resetToToday}
            >
              <Text style={styles.todayResetText}>Today</Text>
            </Pressable>
          )}
        </View>

        <View style={[styles.dateSide, styles.dateSideRight]}>
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Next day"
            hitSlop={8}
            style={styles.dateArrow}
            onPress={() => shiftSelectedDate(1)}
          >
            <Ionicons name="chevron-forward" size={18} color="#111827" />
          </Pressable>
        </View>
      </View>

      {renderContent()}
      <ChildBottomNav
        active="dashboard"
        childId={navChildId}
        name={navName}
        reviewCount={navReviewCount}
      />
      <ChildSwitcherSheet
        visible={switcherOpen}
        childrenList={sortedSwitcherChildren}
        currentChildId={Number(childId)}
        loading={switcherLoading}
        error={switcherError}
        fallbackChild={headerChild}
        onClose={() => setSwitcherOpen(false)}
        onRetry={loadSwitcherChildren}
        onSwitch={switchChild}
        onAddChild={addChildFromSwitcher}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    backgroundColor: "#ffffff",
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  childSwitcherButton: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 8,
  },
  headerAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    overflow: "hidden",
    textAlign: "center",
    lineHeight: 30,
    fontSize: 17,
  },
  headerChildName: {
    maxWidth: 160,
    color: "#111827",
    fontSize: 17,
    fontWeight: "900",
  },
  dateBar: {
    minHeight: 44,
    paddingHorizontal: 16,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    flexDirection: "row",
    alignItems: "center",
  },
  dateSide: {
    width: 44,
    flexDirection: "row",
    alignItems: "center",
  },
  dateSideRight: {
    justifyContent: "flex-end",
  },
  dateArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
  },
  dateCenter: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  dateLabel: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
  todayResetButton: {
    minHeight: 28,
    borderRadius: 999,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  todayResetText: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "800",
  },
  back: {
    fontSize: 16,
    color: "#2563eb",
    fontWeight: "800",
    width: 70,
  },
  title: {
    flex: 1,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "900",
    color: "#111827",
  },
  headerRight: {
    width: 70,
    alignItems: "flex-end",
  },
  targetsText: {
    fontSize: 14,
    color: "#2563eb",
    fontWeight: "700",
  },
  list: {
    padding: 16,
    gap: 12,
    paddingBottom: 112,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    gap: 16,
  },
  errorText: {
    fontSize: 15,
    color: "#dc2626",
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#2563eb",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  retryText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
  },
  scroll: {
    flex: 1,
  },
  summaryBand: {
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  summaryAvatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    overflow: "hidden",
    textAlign: "center",
    lineHeight: 48,
    fontSize: 28,
  },
  summaryText: {
    flex: 1,
  },
  summaryKicker: {
    fontSize: 12,
    color: "#d1d5db",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  summaryName: {
    fontSize: 20,
    color: "#ffffff",
    fontWeight: "900",
    marginTop: 2,
  },
  summarySubline: {
    fontSize: 12,
    color: "#d1d5db",
    fontWeight: "600",
    marginTop: 3,
  },
  summaryStats: {
    alignItems: "flex-end",
    gap: 2,
  },
  summaryStat: {
    fontSize: 13,
    color: "#fbbf24",
    fontWeight: "700",
  },
  summaryStatMuted: {
    fontSize: 13,
    color: "#d1d5db",
    fontWeight: "600",
  },
  warningBanner: {
    backgroundColor: "#fffbeb",
    borderWidth: 1,
    borderColor: "#fde68a",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  warningText: {
    color: "#92400e",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  readOnlyBanner: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  readOnlyBannerText: {
    flex: 1,
    color: "#475569",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  dayStateBanner: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dayStateComplete: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
  },
  dayStateEmpty: {
    backgroundColor: "#f0fdfa",
    borderColor: "#99f6e4",
  },
  dayStateText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  sectionHeader: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
  },
  sectionAction: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "800",
  },
  primarySectionHeader: {
    marginTop: 6,
  },
  primarySectionTitle: {
    color: "#111827",
    fontSize: 26,
    lineHeight: 31,
    fontWeight: "900",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    gap: 10,
    shadowColor: "#0f172a",
    shadowOpacity: 0.035,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  cardReadOnly: {
    shadowOpacity: 0,
    elevation: 0,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cardIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  cardIconText: {
    fontSize: 18,
    fontWeight: "800",
  },
  cardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  cardEyebrow: {
    fontSize: 12,
    color: "#666666",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  cardLabel: {
    fontSize: 17,
    fontWeight: "900",
    color: "#111827",
    marginTop: 1,
  },
  cardAction: {
    fontSize: 14,
    fontWeight: "700",
  },
  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: "800",
  },
  cardDetail: {
    fontSize: 14,
    color: "#475569",
    lineHeight: 20,
  },
  reviewPreviewList: {
    gap: 8,
    marginTop: 2,
  },
  reviewPreview: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 8,
  },
  reviewDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  reviewPreviewText: {
    flex: 1,
    minWidth: 0,
  },
  reviewSurah: {
    fontSize: 14,
    fontWeight: "900",
    color: "#111827",
  },
  reviewRange: {
    fontSize: 12,
    color: "#666666",
    marginTop: 1,
  },
  reviewPriority: {
    fontSize: 12,
    fontWeight: "700",
  },
  moreText: {
    fontSize: 12,
    color: "#666666",
    fontWeight: "600",
  },
  nextCard: {
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  nextCardReadOnly: {
    opacity: 0.72,
  },
  nextNumber: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#dbeafe",
    alignItems: "center",
    justifyContent: "center",
  },
  nextNumberText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "800",
  },
  nextText: {
    flex: 1,
    minWidth: 0,
  },
  nextTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
  },
  nextDetail: {
    color: "#555555",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  nextArabic: {
    color: "#2563eb",
    fontSize: 20,
    fontWeight: "700",
  },
  progressTrack: {
    width: "100%",
    height: 6,
    backgroundColor: "#e5e7eb",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  achievementRow: {
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  achievementIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
  },
  achievementIconEarned: {
    backgroundColor: "#fef3c7",
  },
  achievementEmoji: {
    fontSize: 18,
  },
  achievementText: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  achievementTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  achievementTitle: {
    flex: 1,
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  achievementDetail: {
    color: "#666666",
    fontSize: 12,
    lineHeight: 17,
  },
  earnedText: {
    color: "#b45309",
    fontSize: 11,
    fontWeight: "800",
  },
  achievementProgressText: {
    color: "#666666",
    fontSize: 11,
    fontWeight: "800",
  },
  contentPair: {
    flexDirection: "row",
    gap: 10,
  },
  compactSuggestionCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 70,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  compactSuggestionIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  compactSuggestionText: {
    flex: 1,
    minWidth: 0,
  },
  compactSuggestionTitle: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
  },
  compactSuggestionDetail: {
    color: "#475569",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
  },
  combinedCard: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    overflow: "hidden",
  },
  combinedTabs: {
    flexDirection: "row",
    gap: 6,
    padding: 6,
    backgroundColor: "#f8fafc",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  combinedTab: {
    flex: 1,
    minHeight: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  combinedTabActive: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  combinedTabText: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "900",
  },
  combinedTabTextActive: {
    color: "#111827",
  },
  combinedBody: {
    padding: 14,
    gap: 12,
  },
  goalFocus: {
    gap: 9,
  },
  goalFocusHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  goalFocusTitle: {
    flex: 1,
    minWidth: 0,
    color: "#111827",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "900",
  },
  daysBadge: {
    borderRadius: 999,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  daysBadgeText: {
    color: "#2563eb",
    fontSize: 11,
    fontWeight: "900",
  },
  goalFocusDetail: {
    color: "#475569",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  goalFocusProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  goalFocusMeta: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "800",
  },
  goalFocusPercent: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "900",
  },
  goalFocusDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  goalFocusDateText: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
  },
  combinedRows: {
    marginHorizontal: -14,
    marginTop: -4,
    marginBottom: -4,
  },
  combinedLinkRow: {
    alignSelf: "flex-start",
  },
  combinedLinkText: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "900",
  },
  combinedEmpty: {
    minHeight: 52,
    justifyContent: "center",
  },
  combinedEmptyText: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "700",
  },
  quickGrid: {
    flexDirection: "row",
    gap: 10,
  },
  quickAction: {
    flex: 1,
    minWidth: 0,
    minHeight: 74,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  quickIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  quickText: {
    minWidth: 0,
    alignItems: "center",
  },
  quickTitle: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  quickDetail: {
    color: "#666666",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
    textAlign: "center",
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.34)",
    justifyContent: "flex-end",
  },
  switcherSheet: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingTop: 10,
    paddingHorizontal: 16,
    paddingBottom: 28,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    maxHeight: "78%",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 38,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#cbd5e1",
    marginBottom: 14,
  },
  switcherHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  sheetTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "900",
  },
  sheetSubtitle: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
  },
  sheetCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
  },
  switcherState: {
    minHeight: 150,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  switcherStateText: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "700",
  },
  switcherErrorText: {
    color: "#dc2626",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  switcherRetryButton: {
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  switcherRetryText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  switcherList: {
    maxHeight: 360,
  },
  switcherListContent: {
    gap: 8,
    paddingBottom: 4,
  },
  switcherInlineWarning: {
    backgroundColor: "#fffbeb",
    borderWidth: 1,
    borderColor: "#fde68a",
    borderRadius: 10,
    padding: 10,
  },
  switcherInlineWarningText: {
    color: "#92400e",
    fontSize: 12,
    fontWeight: "700",
  },
  switcherRow: {
    minHeight: 64,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    padding: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  switcherRowSelected: {
    backgroundColor: "#f8fafc",
    borderColor: "#bfdbfe",
  },
  switcherAvatar: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
  },
  switcherAvatarText: {
    fontSize: 22,
  },
  switcherText: {
    flex: 1,
    minWidth: 0,
  },
  switcherName: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
  },
  switcherMeta: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
  switcherSelectedBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ecfdf5",
    borderWidth: 1,
    borderColor: "#a7f3d0",
    alignItems: "center",
    justifyContent: "center",
  },
  switcherAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  switcherActionText: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "800",
  },
  addChildRow: {
    marginTop: 12,
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#bfdbfe",
    backgroundColor: "#f8fbff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  addChildIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#eff6ff",
    alignItems: "center",
    justifyContent: "center",
  },
  addChildText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "900",
  },
});
