import { useCallback, useState, type ComponentProps, type ReactNode } from "react";
import {
  ActivityIndicator,
  Alert,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  View,
  type StyleProp,
  type ColorValue,
  type ViewStyle,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { ChildBottomNav } from "@/src/components/child-bottom-nav";
import { ApiError, apiFetch } from "@/src/lib/api";
import {
  fetchHafidhProjections,
  type ProjectionResponse,
  type ProjectionTier,
} from "@/src/lib/projections";
import { APP_ADAPTIVE_COLORS as appColors } from "@/src/lib/app-theme";

type IconName = ComponentProps<typeof Ionicons>["name"];

type PlanChild = {
  name: string;
  avatarEmoji: string;
};

type DashboardResponse = {
  child: PlanChild;
  reviewsDueToday: number;
};

type Goal = {
  id: string;
  title: string;
  description: string;
  targetDate?: string;
  targetSurahCount: number;
  currentCount: number;
  type?: string;
  autoGenerated?: boolean;
};

type CurrentPhase = {
  phaseName: string;
  description: string;
  surahs: string[];
};

type WeeklyGoal = {
  memorizationDays: number;
  reviewDays: number;
  storyDays: number;
  duasDays: number;
};

type Milestone = {
  id: string;
  title: string;
  description: string;
  targetSurahs: string[];
  reward: string;
};

type TajweedRule = {
  rule: string;
  description: string;
  ageIntroduced: number;
};

type PlanResponse = {
  ageGroup: "toddler" | "child" | "preteen" | "teen" | string;
  description: string;
  currentPhase: CurrentPhase;
  weeklyGoal: WeeklyGoal;
  milestones: Milestone[];
  tajweedRules: TajweedRule[];
  goals: Goal[];
  practiceMinutesPerDay: number;
};

type PlanState =
  | { status: "loading" }
  | { status: "error"; message: string }
  | {
      status: "ready";
      plan: PlanResponse;
      dashboard: DashboardResponse;
      projection: ProjectionResponse | null;
    };

const AGE_GROUP_LABELS: Record<string, string> = {
  toddler: "Seeds of Faith (Ages 3–6)",
  child: "Building Foundation (Ages 7–10)",
  preteen: "Deepening Knowledge (Ages 11–14)",
  teen: "Path to Hifz (Ages 15+)",
};

const WEEKLY_TILES: Array<{
  key: keyof WeeklyGoal;
  label: string;
  color: ColorValue;
  backgroundColor: ColorValue;
  borderColor: ColorValue;
}> = [
  {
    key: "memorizationDays",
    label: "Memorization days",
    color: appColors.primary,
    backgroundColor: appColors.primarySoft,
    borderColor: appColors.primaryBorder,
  },
  {
    key: "reviewDays",
    label: "Review days",
    color: appColors.warning,
    backgroundColor: appColors.warningSoft,
    borderColor: appColors.warningBorder,
  },
  {
    key: "storyDays",
    label: "Story days",
    color: "#0891b2",
    backgroundColor: appColors.primarySoft,
    borderColor: appColors.primaryBorder,
  },
  {
    key: "duasDays",
    label: "Du'a days",
    color: appColors.danger,
    backgroundColor: appColors.dangerSoft,
    borderColor: appColors.dangerBorder,
  },
];

function isValidChildId(childId: string | undefined): childId is string {
  return typeof childId === "string" && /^\d+$/.test(childId);
}

function describeError(error: unknown) {
  if (error instanceof ApiError) {
    return `${error.message} (${error.path})`;
  }
  if (error instanceof Error) {
    return error.message;
  }
  return "Failed to load the learning plan.";
}

function parseLocalDate(value: string | undefined) {
  if (!value) return null;
  const date = new Date(`${value}T12:00:00`);
  return Number.isNaN(date.getTime()) ? null : date;
}

function getLocalDateValue() {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function getDaysLeft(targetDate: string | undefined) {
  const target = parseLocalDate(targetDate);
  const today = parseLocalDate(getLocalDateValue());
  if (!target || !today) return null;
  return Math.max(0, Math.ceil((target.getTime() - today.getTime()) / 86_400_000));
}

function formatDaysLeft(days: number | null) {
  if (days == null) return "Target pending";
  if (days === 0) return "Due today";
  return `${days} day${days === 1 ? "" : "s"} left`;
}

function formatTargetDate(value: string | undefined) {
  const date = parseLocalDate(value);
  if (!date) return null;
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatProjectedDate(value: string | null) {
  return formatTargetDate(value ?? undefined) ?? "Not enough pace";
}

function getWeeksBetween(startValue: string, endValue: string) {
  const start = parseLocalDate(startValue);
  const end = parseLocalDate(endValue);
  if (!start || !end) return null;
  return Math.ceil((end.getTime() - start.getTime()) / (86_400_000 * 7));
}

function getRequiredPagesPerDay(
  pagesRemaining: number,
  targetDate: string | null,
  memorizationDays: number,
) {
  if (!targetDate || pagesRemaining <= 0) return null;
  const weeks = getWeeksBetween(getLocalDateValue(), targetDate);
  if (weeks == null || weeks <= 0) return null;
  const days = Math.max(1, memorizationDays);
  return Math.ceil((pagesRemaining / (weeks * days)) * 100) / 100;
}

function formatPercent(value: number, target: number) {
  if (target <= 0) return 0;
  return Math.max(0, Math.min(100, Math.round((value / target) * 100)));
}

function Header({
  child,
  childId,
  fallbackName,
}: {
  child: PlanChild | null;
  childId: string | undefined;
  fallbackName: string;
}) {
  const router = useRouter();
  const displayName = child?.name ?? fallbackName ?? "Plan";

  function goDashboard() {
    if (!isValidChildId(childId)) {
      router.back();
      return;
    }

    router.replace({
      pathname: "/child/[childId]",
      params: { childId, name: displayName },
    });
  }

  function openSettings() {
    if (!isValidChildId(childId)) return;
    router.push({
      pathname: "/child/[childId]/targets",
      params: { childId, name: displayName },
    });
  }

  return (
    <View style={styles.header}>
      <Pressable
        accessibilityRole="button"
        accessibilityLabel="Back to dashboard"
        hitSlop={8}
        style={styles.headerIconButton}
        onPress={goDashboard}
      >
        <Ionicons name="chevron-back" size={22} color={appColors.text as string} />
      </Pressable>

      <View style={styles.headerIdentity}>
        <Text style={styles.headerAvatar}>{child?.avatarEmoji ?? "?"}</Text>
        <Text style={styles.headerChildName} numberOfLines={1}>
          {displayName}
        </Text>
      </View>

      <Pressable
        accessibilityRole="button"
        accessibilityLabel="Open child settings"
        hitSlop={8}
        style={styles.headerIconButton}
        onPress={openSettings}
      >
        <Ionicons name="settings-outline" size={21} color={appColors.text as string} />
      </Pressable>
    </View>
  );
}

function Card({
  children,
  style,
}: {
  children: ReactNode;
  style?: StyleProp<ViewStyle>;
}) {
  return <View style={[styles.card, style]}>{children}</View>;
}

function CardTitle({
  iconName,
  iconColor,
  title,
  right,
}: {
  iconName: IconName;
  iconColor: string;
  title: string;
  right?: ReactNode;
}) {
  return (
    <View style={styles.cardTitleRow}>
      <View style={styles.cardTitleLeft}>
        <View style={[styles.titleIcon, { backgroundColor: `${iconColor}14` }]}>
          <Ionicons name={iconName} size={17} color={iconColor} />
        </View>
        <Text style={styles.cardTitle}>{title}</Text>
      </View>
      {right}
    </View>
  );
}

function ProgressBar({
  value,
  color,
}: {
  value: number;
  color: string;
}) {
  return (
    <View style={styles.progressTrack}>
      <View style={[styles.progressFill, { width: `${value}%`, backgroundColor: color }]} />
    </View>
  );
}

function GoalCard({ goal }: { goal: Goal }) {
  const current = goal.currentCount ?? 0;
  const target = goal.targetSurahCount ?? 0;
  const completed = target > 0 && current >= target;
  const percent = completed ? 100 : formatPercent(current, target);
  const daysLeft = getDaysLeft(goal.targetDate);
  const targetLabel = formatTargetDate(goal.targetDate);

  return (
    <View style={[styles.goalCard, completed && styles.goalCardComplete]}>
      <View style={styles.goalHeader}>
        <View style={styles.goalTitleBlock}>
          <Text style={styles.goalTitle} numberOfLines={2}>
            {goal.title}
          </Text>
          <Text style={styles.goalDescription}>{goal.description}</Text>
        </View>
        {completed ? (
          <View style={styles.completedBadge}>
            <Text style={styles.completedBadgeText}>🏆 Completed!</Text>
          </View>
        ) : (
          <View style={styles.daysBadge}>
            <Text style={styles.daysBadgeText}>{formatDaysLeft(daysLeft)}</Text>
          </View>
        )}
      </View>

      <ProgressBar value={percent} color={completed ? "#059669" : "#2563eb"} />

      <View style={styles.goalProgressRow}>
        <Text style={styles.goalCountText}>
          {current} / {target} surahs
        </Text>
        <Text style={styles.goalPercentText}>{percent}%</Text>
      </View>

      {!completed && targetLabel ? (
        <Text style={styles.targetDateText}>Target: {targetLabel}</Text>
      ) : null}
    </View>
  );
}

function WeeklyTile({
  label,
  value,
  color,
  backgroundColor,
  borderColor,
}: {
  label: string;
  value: number;
  color: ColorValue;
  backgroundColor: ColorValue;
  borderColor: ColorValue;
}) {
  return (
    <View style={[styles.weeklyTile, { backgroundColor, borderColor }]}>
      <Text style={[styles.weeklyValue, { color }]}>{value}</Text>
      <Text style={styles.weeklyLabel}>{label}</Text>
    </View>
  );
}

function MilestoneRow({
  milestone,
  isLast,
}: {
  milestone: Milestone;
  isLast: boolean;
}) {
  return (
    <View style={[styles.milestoneRow, !isLast && styles.separatedRow]}>
      <Text style={styles.rowTitle}>{milestone.title}</Text>
      <Text style={styles.rowDescription}>{milestone.description}</Text>
      <Text style={styles.rewardText}>{milestone.reward}</Text>
      <Text style={styles.footerLine}>
        {milestone.targetSurahs.join(", ")}
      </Text>
    </View>
  );
}

function TajweedRuleRow({
  rule,
  isLast,
}: {
  rule: TajweedRule;
  isLast: boolean;
}) {
  return (
    <View style={[styles.tajweedRow, !isLast && styles.separatedRow]}>
      <View style={styles.ruleBody}>
        <Text style={styles.rowTitle}>{rule.rule}</Text>
        <Text style={styles.rowDescription}>{rule.description}</Text>
      </View>
      <View style={styles.agePill}>
        <Text style={styles.agePillText}>Age {rule.ageIntroduced}</Text>
      </View>
    </View>
  );
}

function HafidhProjectionCard({
  projection,
  memorizationDays,
}: {
  projection: ProjectionResponse;
  memorizationDays: number;
}) {
  const activeTier =
    projection.tiers.find((tier) => tier.tier === projection.activeTier) ??
    projection.tiers.find((tier) => tier.tier === "full_hafidh") ??
    projection.tiers[projection.tiers.length - 1];
  if (!activeTier) return null;

  const targetLabel = formatTargetDate(projection.targetDate ?? undefined);
  const requiredPagesPerDay = getRequiredPagesPerDay(
    activeTier.pagesRemaining,
    projection.targetDate,
    memorizationDays,
  );
  const targetStatusText =
    projection.targetDate == null
      ? null
      : activeTier.meetsExplicitTarget
      ? `Will meet target date ${targetLabel ?? ""}`.trim()
      : requiredPagesPerDay != null
      ? `Increase to ${requiredPagesPerDay} page${requiredPagesPerDay === 1 ? "" : "s"}/day to stay on track`
      : "Current pace is behind the target date";

  return (
    <Card>
      <CardTitle iconName="map-outline" iconColor="#ea580c" title="Hafidh Projection" />
      <View style={styles.projectionHero}>
        <Text style={styles.projectionKicker}>{activeTier.label}</Text>
        <Text style={styles.projectionDate}>{formatProjectedDate(activeTier.projectedCompletionDate)}</Text>
        <Text style={styles.projectionMeta}>
          {projection.pacePagesPerWeek.toFixed(2).replace(/\.00$/, "")} pages/week ·{" "}
          {activeTier.pagesRemaining} page{activeTier.pagesRemaining === 1 ? "" : "s"} left
        </Text>
      </View>

      {targetStatusText ? (
        <View
          style={[
            styles.targetStatus,
            activeTier.meetsExplicitTarget ? styles.targetStatusGood : styles.targetStatusWarning,
          ]}
        >
          <Ionicons
            name={activeTier.meetsExplicitTarget ? "checkmark-circle-outline" : "alert-circle-outline"}
            size={16}
            color={(activeTier.meetsExplicitTarget ? appColors.success : appColors.warning) as string}
          />
          <Text
            style={[
              styles.targetStatusText,
              activeTier.meetsExplicitTarget ? styles.targetStatusTextGood : styles.targetStatusTextWarning,
            ]}
          >
            {targetStatusText}
          </Text>
        </View>
      ) : null}

      <View style={styles.projectionTierList}>
        {projection.tiers.map((tier: ProjectionTier) => (
          <View key={tier.tier} style={styles.projectionTierRow}>
            <View style={styles.projectionTierText}>
              <Text style={styles.projectionTierTitle}>{tier.label}</Text>
              <Text style={styles.projectionTierDetail}>
                {tier.pagesRemaining} of {tier.totalPages} pages left
              </Text>
            </View>
            <Text style={styles.projectionTierDate}>
              {formatProjectedDate(tier.projectedCompletionDate)}
            </Text>
          </View>
        ))}
      </View>
    </Card>
  );
}

export default function PlanScreen() {
  const { childId, name } = useLocalSearchParams<{ childId: string; name: string }>();
  const [state, setState] = useState<PlanState>({ status: "loading" });
  const [refreshing, setRefreshing] = useState(false);
  const [resetting, setResetting] = useState(false);
  const fallbackName = typeof name === "string" ? name : "Plan";

  const loadPlan = useCallback(
    async (mode: "focus" | "refresh" = "focus") => {
      if (!isValidChildId(childId)) {
        setState({
          status: "error",
          message: "This plan route is missing a valid child id.",
        });
        return;
      }

      if (mode === "refresh") {
        setRefreshing(true);
      } else {
        setState((current) => current.status === "ready" ? current : { status: "loading" });
      }

      try {
        const [plan, dashboard, projection] = await Promise.all([
          apiFetch<PlanResponse>(`/api/children/${childId}/plan`),
          apiFetch<DashboardResponse>(`/api/children/${childId}/dashboard?preview=true`),
          fetchHafidhProjections(childId).catch(() => null),
        ]);
        setState({ status: "ready", plan, dashboard, projection });
      } catch (error) {
        setState({ status: "error", message: describeError(error) });
      } finally {
        setRefreshing(false);
      }
    },
    [childId],
  );

  useFocusEffect(
    useCallback(() => {
      void loadPlan("focus");
    }, [loadPlan]),
  );

  const child = state.status === "ready" ? state.dashboard.child : null;
  const plan = state.status === "ready" ? state.plan : null;
  const projection = state.status === "ready" ? state.projection : null;
  const practiceMinutes = plan?.practiceMinutesPerDay ?? 20;

  async function resetGoals() {
    if (!isValidChildId(childId)) return;

    setResetting(true);
    try {
      await apiFetch<{ success: boolean; goals: null }>(`/api/children/${childId}/goals`, {
        method: "PUT",
        body: JSON.stringify({ goals: null }),
      });
      await loadPlan("refresh");
    } catch (error) {
      Alert.alert("Could not reset goals", describeError(error));
    } finally {
      setResetting(false);
    }
  }

  function confirmResetGoals() {
    Alert.alert(
      "Reset goals?",
      "NoorPath will replace these goals with the auto-calculated plan for this child.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Reset",
          style: "destructive",
          onPress: () => {
            void resetGoals();
          },
        },
      ],
    );
  }

  return (
    <View style={styles.container}>
      <Header child={child} childId={childId} fallbackName={fallbackName} />

      {state.status === "loading" ? (
        <View style={styles.center}>
          <ActivityIndicator size="large" color="#2563eb" />
        </View>
      ) : state.status === "error" ? (
        <View style={styles.center}>
          <View style={styles.errorCard}>
            <Ionicons name="alert-circle-outline" size={24} color="#dc2626" />
            <Text style={styles.errorText}>{state.message}</Text>
          </View>
          <Pressable style={styles.retryButton} onPress={() => loadPlan("focus")}>
            <Text style={styles.retryText}>Retry</Text>
          </Pressable>
        </View>
      ) : plan ? (
        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.list}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={() => loadPlan("refresh")}
              tintColor="#2563eb"
            />
          }
        >
          <View style={styles.titleBlock}>
            <Text style={styles.pageTitle} numberOfLines={3}>
              {AGE_GROUP_LABELS[plan.ageGroup] ?? AGE_GROUP_LABELS.child}
            </Text>
            <View style={styles.practicePill}>
              <Ionicons name="time-outline" size={14} color="#2563eb" />
              <Text style={styles.practiceText}>{practiceMinutes} min/day</Text>
            </View>
          </View>

          {plan.goals.length > 0 ? (
            <Card>
              <CardTitle
                iconName="trophy-outline"
                iconColor="#d97706"
                title="Your Goals"
                right={
                  <Pressable
                    accessibilityRole="button"
                    disabled={resetting}
                    hitSlop={8}
                    onPress={confirmResetGoals}
                  >
                    <Text style={[styles.resetText, resetting && styles.resetTextDisabled]}>
                      {resetting ? "Resetting..." : "Reset to auto"}
                    </Text>
                  </Pressable>
                }
              />
              <View style={styles.goalList}>
                {plan.goals.map((goal) => (
                  <GoalCard key={goal.id} goal={goal} />
                ))}
              </View>
              <Text style={styles.goalsFooter}>
                Goals are auto-calculated based on your {practiceMinutes} min/day practice time
              </Text>
            </Card>
          ) : null}

          {projection ? (
            <HafidhProjectionCard
              projection={projection}
              memorizationDays={plan.weeklyGoal.memorizationDays}
            />
          ) : null}

          <Card>
            <Text style={styles.descriptionText}>{plan.description}</Text>
          </Card>

          <Card>
            <CardTitle iconName="locate-outline" iconColor="#2563eb" title="Current Phase" />
            <View style={styles.phasePill}>
              <Text style={styles.phasePillText}>{plan.currentPhase.phaseName}</Text>
            </View>
            <Text style={styles.bodyText}>{plan.currentPhase.description}</Text>
            <View style={styles.chipWrap}>
              {plan.currentPhase.surahs.map((surah) => (
                <View key={surah} style={styles.surahChip}>
                  <Text style={styles.surahChipText}>{surah}</Text>
                </View>
              ))}
            </View>
          </Card>

          <Card>
            <CardTitle iconName="calendar-outline" iconColor="#2563eb" title="Weekly Goals" />
            <View style={styles.weeklyGrid}>
              {WEEKLY_TILES.map((tile) => (
                <WeeklyTile
                  key={tile.key}
                  label={tile.label}
                  value={plan.weeklyGoal[tile.key]}
                  color={tile.color}
                  backgroundColor={tile.backgroundColor}
                  borderColor={tile.borderColor}
                />
              ))}
            </View>
          </Card>

          {plan.milestones.length > 0 ? (
            <Card>
              <CardTitle iconName="star-outline" iconColor="#d97706" title="Milestones" />
              <View style={styles.rowList}>
                {plan.milestones.map((milestone, index) => (
                  <MilestoneRow
                    key={milestone.id}
                    milestone={milestone}
                    isLast={index === plan.milestones.length - 1}
                  />
                ))}
              </View>
            </Card>
          ) : null}

          {plan.tajweedRules.length > 0 ? (
            <Card>
              <CardTitle iconName="book-outline" iconColor="#0f766e" title="Tajweed Rules" />
              <View style={styles.rowList}>
                {plan.tajweedRules.map((rule, index) => (
                  <TajweedRuleRow
                    key={rule.rule}
                    rule={rule}
                    isLast={index === plan.tajweedRules.length - 1}
                  />
                ))}
              </View>
            </Card>
          ) : null}
        </ScrollView>
      ) : null}

      <ChildBottomNav
        active="more"
        childId={childId}
        name={child?.name ?? fallbackName}
        reviewCount={state.status === "ready" ? state.dashboard.reviewsDueToday : undefined}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: appColors.border,
    backgroundColor: appColors.surface,
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  headerIdentity: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 8,
  },
  headerAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: appColors.surfaceSubtle,
    borderWidth: 1,
    borderColor: appColors.border,
    overflow: "hidden",
    textAlign: "center",
    lineHeight: 30,
    fontSize: 17,
  },
  headerChildName: {
    maxWidth: 185,
    color: appColors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  scroll: {
    flex: 1,
  },
  list: {
    padding: 16,
    gap: 12,
    paddingBottom: 112,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    gap: 16,
  },
  errorCard: {
    width: "100%",
    borderWidth: 1,
    borderColor: appColors.dangerBorder,
    borderRadius: 12,
    backgroundColor: appColors.dangerSoft,
    padding: 18,
    alignItems: "center",
    gap: 10,
  },
  errorText: {
    color: appColors.danger,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  retryText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  titleBlock: {
    gap: 9,
    paddingTop: 2,
    paddingBottom: 2,
  },
  pageTitle: {
    color: appColors.text,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  practicePill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: appColors.primarySoft,
    borderWidth: 1,
    borderColor: appColors.primaryBorder,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  practiceText: {
    color: appColors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  card: {
    backgroundColor: appColors.surface,
    borderWidth: 1,
    borderColor: appColors.border,
    borderRadius: 12,
    padding: 14,
    gap: 12,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  cardTitleLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  titleIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitle: {
    color: appColors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  resetText: {
    color: appColors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  resetTextDisabled: {
    color: appColors.textSubtle,
  },
  goalList: {
    gap: 10,
  },
  goalCard: {
    borderWidth: 1,
    borderColor: appColors.border,
    borderRadius: 12,
    backgroundColor: appColors.surface,
    padding: 12,
    gap: 9,
  },
  goalCardComplete: {
    borderColor: appColors.successBorder,
    backgroundColor: appColors.successSoft,
  },
  goalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  goalTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  goalTitle: {
    color: appColors.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  goalDescription: {
    color: appColors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  daysBadge: {
    flexShrink: 0,
    borderWidth: 1,
    borderColor: appColors.primaryBorder,
    backgroundColor: appColors.primarySoft,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  daysBadgeText: {
    color: appColors.primary,
    fontSize: 11,
    fontWeight: "900",
  },
  completedBadge: {
    flexShrink: 0,
    borderWidth: 1,
    borderColor: appColors.successBorder,
    backgroundColor: appColors.successSoft,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  completedBadgeText: {
    color: appColors.success,
    fontSize: 11,
    fontWeight: "900",
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: appColors.border,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  goalProgressRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  goalCountText: {
    color: appColors.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  goalPercentText: {
    color: appColors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  targetDateText: {
    color: appColors.textMuted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  goalsFooter: {
    color: appColors.textMuted,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  projectionHero: {
    borderWidth: 1,
    borderColor: appColors.warningBorder,
    backgroundColor: appColors.warningSoft,
    borderRadius: 12,
    padding: 14,
    gap: 4,
  },
  projectionKicker: {
    color: appColors.warning,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  projectionDate: {
    color: appColors.text,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  projectionMeta: {
    color: appColors.warning,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  targetStatus: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  targetStatusGood: {
    borderColor: appColors.successBorder,
    backgroundColor: appColors.successSoft,
  },
  targetStatusWarning: {
    borderColor: appColors.warningBorder,
    backgroundColor: appColors.warningSoft,
  },
  targetStatusText: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "900",
  },
  targetStatusTextGood: {
    color: appColors.success,
  },
  targetStatusTextWarning: {
    color: appColors.warning,
  },
  projectionTierList: {
    borderTopWidth: 1,
    borderTopColor: appColors.border,
  },
  projectionTierRow: {
    minHeight: 54,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: appColors.separator,
  },
  projectionTierText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  projectionTierTitle: {
    color: appColors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  projectionTierDetail: {
    color: appColors.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  projectionTierDate: {
    flexShrink: 0,
    maxWidth: 124,
    color: appColors.primary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    textAlign: "right",
  },
  descriptionText: {
    color: appColors.textMuted,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
  },
  phasePill: {
    alignSelf: "flex-start",
    backgroundColor: appColors.primarySoft,
    borderWidth: 1,
    borderColor: appColors.primaryBorder,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  phasePillText: {
    color: appColors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  bodyText: {
    color: appColors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  surahChip: {
    backgroundColor: appColors.surfaceSubtle,
    borderWidth: 1,
    borderColor: appColors.border,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 9,
  },
  surahChipText: {
    color: appColors.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  weeklyGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  weeklyTile: {
    width: "48%",
    minHeight: 86,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  weeklyValue: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "900",
  },
  weeklyLabel: {
    color: appColors.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 3,
  },
  rowList: {
    marginHorizontal: -2,
  },
  separatedRow: {
    borderBottomWidth: 1,
    borderBottomColor: appColors.border,
  },
  milestoneRow: {
    paddingVertical: 11,
    paddingHorizontal: 2,
    gap: 5,
  },
  rowTitle: {
    color: appColors.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  rowDescription: {
    color: appColors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  rewardText: {
    color: appColors.warning,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "900",
  },
  footerLine: {
    color: appColors.textSubtle,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  tajweedRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 11,
    paddingHorizontal: 2,
  },
  ruleBody: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  agePill: {
    flexShrink: 0,
    borderWidth: 1,
    borderColor: appColors.successBorder,
    backgroundColor: appColors.successSoft,
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  agePillText: {
    color: appColors.success,
    fontSize: 11,
    fontWeight: "900",
  },
});
